### ISSUE TITLE
DB Saved on disk delete my active jobs

### ISSUE THREAD

**Issue by devmetal** [bee-queue/bee-queue#100]
Hi guys, pls correct me if i'm wrong or my redis configuration is not suitable for this but i have a big strange issue. I use bee-queue (awesome anyway, is life saver i love it) but maybe my redis server config is wrong. 

The problem: I use bee-queue for run a job loop. Its an endless cycle of jobs. When a worker is done, its send a job for an other, and etc, and when the process is end, the last worker just send the same job again to the first worker. Its fine its working, but not stable. 

Every time approximately 8 hours after, the arena shows me 0 active jobs. Nothing, when i start to dig my log files i saw a record from redis itself: **1:M 20 Feb 00:39:37.205 * DB saved on disk** From this line, the job queue is not logging anymore except the check stalled jobs messages. 

I don't know whats the problem. I use docker and docker-compose and i don't set any config to redis, just start a simple image without any options. Can you give me some advice or maybe a solution for this? 

I use **docker**
bee-queue version: **1.2.0**
redis docker file:

```
FROM redis
EXPOSE 6379
```

[Edited]
Maybe the problem is the most of my jobs are pending state? I mean, my job queue size is 240 item. When one item is under process the most of is waiting. Maybe the redis will "delete" this pending jobs when its saving backups to disk?

Thank you for help and advices.

**Comment by devmetal** [comment]
Hi, it happend again. Pls can anybody help with my issue?

**Comment by dylanjha** [comment]
@devmetal Based in the information provided it's tough to tell. See if you can create a minimum reproducible example in a script or a repo to reproduce this issue. If it is reproducible, it is much more likely that someone can debug it.

If keys jobs are mysteriously disappearing one thought is that this might be related to your redis Maxmemory policy. Check what the configuration is.

Redis has a feature called `maxmemory-policy`. This instructs Redis about what to do when the DB runs out of space and will no longer fit in-memory. For example you can tell Redis that if there is no more space then simply start throwing errors (`noeviction`) or to remove the oldest keys first (`allkeys-lru`), or remove random keys (`allkeys-random`), etc. Full list of options in the docs: https://redis.io/topics/lru-cache#eviction-policies

Lastly, it doesn't seem like a good pattern to run the same job in a continuous loop. If you can't replicate, can you post some example code? Jobs are not meant to be re-used. They should be run and discarded. If you need to do more work then queue another job, don't try to re-use the same one. It seems fairly likely that this could be causing your issue.

**Comment by LewisJEllis** [comment]
Yea, I can't really imagine any scenarios here related to Redis configuration - both of Redis's backup methods (RDB or AOF)  are pretty well-understood and shouldn't affect existing data in memory.

I've seen situations where jobs will be repeated after a Redis restart due to the at-least-once retry mechanics, but I have not experienced loss of pending or active jobs. It's possible that you could lose recently-enqueued jobs if your Redis process restarts between when they're enqueued and when it persists them, but it doesn't sound like that's what's happening here.

It's possible your jobs-in-a-loop scenario is outside of originally design's intended usage, but I'm not sure. Example code or a more detailed description of your job cycle would help a lot.

Are you using a single queue for all this, or is it a series of queues where (for example) Queue A's worker enqueues to Queue B, whose worker enqueues to Queue C, whose worker enqueues to Queue A?

Do you have just one active job at any given time, or are there sometimes multiple cycles in progress? What are the 240 jobs in the queue? I'm curious how that gets backed up.

**Comment by devmetal** [comment]
Thank you for the answers. So, i created a scraper. We scraping rss feeds and i wanted to use a redis job queue. The entry point is RssScraper. When this parsed one site, create a job for the RssSaver, Notifications, Meta and etc.. The most of workers are simple, just one or two mongodb operation. But the RssScraper is slower then others because of the http requests. When the meta queue is done, is create a new job and add to RssScraper. I'm not reusing just create a new one. I'll try provide some example code, but its a lot. Every single worker run a different docker container and i use dokcer-compose for build and run. 

I share the RssScraper and the last worker code.

RssScraper
```JavaScript

const rssScraperQueue = new Queue(queues.rssScraper, {
  redis: { port, host },
  removeOnSuccess: true,
  removeOnFailure: true,
  stallInterval: 5000,
});

const rssSaverQueue = new Queue(queues.rssSaver, {
  redis: { port, host },
  isWorker: false,
});

const rssMetaQueue = new Queue(queues.rssMeta, {
  redis: { port, host },
  isWorker: false,
});

rssScraperQueue.process(async (job) => {
  log.info('Job landed', {
    jobId: job.id,
    data: job.data,
  });

  const { siteDocId } = job.data;
  const site = await SiteModel.findById(siteDocId);
  const meta = await SiteMetaModel.findOne({ siteId: siteDocId });

  if (meta && meta.unreadable === true) {
    log.warn('unreadable', siteDocId);
    return;
  }

  const rssLink = getRssLink(site);

  try {
    const feedContent = await getFeed(rssLink);
    const feed = await parse(feedContent);

    const metaJob = rssMetaQueue.createJob({
      siteId: siteDocId,
      success: true,
    });

    const saverJob = rssSaverQueue.createJob({
      _id: siteDocId,
      feed,
      rssLink,
    });

    await Promise.all([
      metaJob.save(),
      saverJob.save(),
    ]);

    log.info('Job done', job.id);
  } catch (error) {
    const metaJob = rssMetaQueue.createJob({
      siteId: siteDocId,
      success: false,
      reason: error.message,
      stack: error.stack,
    });

    await metaJob.save();
    log.info('Job done', job.id);
  }
});

rssScraperQueue.on('error', error => log.error(error));

rssScraperQueue.on('failed', (job, error) => {
  log.error('Job failed', pick(job, ['data', 'id']), error);
});

rssScraperQueue.on('stalled', job =>
  log.error('Job stalled', pick(job, ['data', 'id'])));

rssScraperQueue.on('succeeded', (job) => {
  log.info('Job completed, now remove', pick(job, ['data', 'id']));
});

rssScraperQueue.checkStalledJobs(5000, (err, numStalled) => {
  log.warn('Checked stalled jobs', numStalled);
});

log.info('Rss Worker Ready');
```

RssMeta
```JavaScript
const rssMetaQueue = new Queue(queues.rssMeta, {
  redis: { port, host },
  removeOnSuccess: true,
  removeOnFailure: true,
});

const rssScraperQueue = new Queue(queues.rssScraper, {
  redis: { port, host },
  isWorker: false,
});

rssMetaQueue.process(async (job) => {
  log.info('Job landed', {
    jobId: job.id,
    data: job.data,
  });

  const {
    siteId,
    success,
    reason,
    stack,
  } = job.data;

  const options = await OptionsModel.findOne({});
  const siteMeta = await SiteMetaModel.findOne({
    siteId,
  });

  if (!siteMeta) {
    const rssScraping = { siteId };

    if (success) {
      rssScraping.lastSuccess = moment().toDate();
      rssScraping.attempts = 0;
    } else {
      rssScraping.lastFail = moment().toDate();
      rssScraping.attempts = 1;
      rssScraping.lastError = reason;
      rssScraping.lastErrorStack = stack;
    }

    await SiteMetaModel.create(rssScraping);

    const scraperJob = rssScraperQueue.createJob({
      siteDocId: job.data.siteId,
    });
    await scraperJob.timeout(rssScraperTimeout).save();
    return;
  }

  if (success) {
    await siteMeta.update({
      $set: {
        lastSuccess: moment().toDate(),
        attempts: 0,
      },
    });
  } else {
    const { maxAttempts } = options.rssScraper;
    if (siteMeta.attempts + 1 >= maxAttempts) {
      await siteMeta.update({
        $set: {
          unreadable: true,
          lastError: reason,
          lastErrorStack: stack,
          lastFail: moment().toDate(),
        },
      });
    } else {
      await siteMeta.update({
        $inc: {
          attempts: 1,
        },
        $set: {
          lastError: reason,
          lastErrorStack: stack,
          lastFail: moment().toDate(),
        },
      });
    }
  }

  const scraperJob = rssScraperQueue.createJob({
    siteDocId: job.data.siteId,
  });
  await scraperJob.timeout(rssScraperTimeout).save();
});

rssMetaQueue.on('error', error => log.error(error));

rssMetaQueue.on('failed', (job, error) =>
  log.error('Job failed', pick(job, ['data', 'id']), error));

rssMetaQueue.on('stalled', job =>
  log.error('Job stalled', pick(job, ['data', 'id'])));

rssMetaQueue.on('succeeded', (job) => {
  log.info('Job completed, now remove', pick(job, ['data', 'id']));
});

rssMetaQueue.checkStalledJobs(5000, (err, numStalled) => {
  // prints the number of stalled jobs detected every 5000 ms
  log.warn('Checked stalled jobs', numStalled);
});

module.exports = rssMetaQueue;
```

I know the meta queue code is ugly but the last operation is create a new job for a scraper. 

You mentioned maybe my solution is not fit the original concept of job queue. I think i understand that. I tried earlyer the node-scheduler for every 5min restart the jobs but in our problem, its really important the fast and almost real time reading. 

Thank you for support :)
