### ISSUE TITLE
Code coverage is actually at 100%

### ISSUE THREAD

**Issue by scriptcoded** [bee-queue/bee-queue#105]
Just thought you might want to update your readme. I mean, you do actually have 100% code coverage ;)

[![Coverage Status][coveralls-image]][coveralls-url]
> Robust: designed with concurrency, atomicity, and failure in mind; **close to** full code coverage.

[coveralls-image]: https://coveralls.io/repos/bee-queue/bee-queue/badge.svg?branch=master
[coveralls-url]: https://coveralls.io/r/bee-queue/bee-queue?branch=master

**Comment by bradvogel** [comment]
🎉
