### ISSUE TITLE
An effective way to clean up completed jobs?

### ISSUE THREAD

**Issue by indatawetrust** [bee-queue/bee-queue#113]
How can I clean up tasks that are completed in a queue that is constantly assigned new jobs? I use job.remove() after the job is done, but it does not seem to work very well.

**Comment by indatawetrust** [comment]
I tried removeOnSuccess. looks good for now.

**Comment by rmsouza** [comment]
Even when an error occurred and removeOnSuccess: false, my jobs are being removed. Anything else I need to configure?

**Comment by dylanjha** [comment]
@rmsouza `removeOnSuccess` is working as documented. If possible try to post a code snippet with an example so someone can help.

One idea off the top of my head when you say an error occurred make sure that the error is happening in the context of the job processing function. If you are doing things asynchronously in the process function you should either return a promise or use the `done()` callback. https://github.com/bee-queue/bee-queue#processing-jobs

**Comment by skeggse** [comment]
>Even when an error occurred and removeOnSuccess: false, my jobs are being removed. Anything else I need to configure?

Are you looking for the `removeOnFailure` option?
