### ISSUE TITLE
can't passing any data in job progress 

### ISSUE THREAD

**Issue by hbakhtiyor** [bee-queue/bee-queue#118]
`job.reportProgress(anyData)`

the error
`Error: Progress must be between 0 and 100`

i think need a bit generic progress method which accept data, not just numbers, like [job progress of kue](https://github.com/Automattic/kue#job-progress) 
```
job.progress(completed, total [, data])
```

**Comment by hbakhtiyor** [comment]
@LewisJEllis dups with https://github.com/bee-queue/bee-queue/issues/39, but still not publish the patch?

**Comment by jgburet** [comment]
Also waiting for that release :(

**Comment by skeggse** [comment]
Duplicate of #39. This was released in `1.2.3`, and fixed in #109.

**Comment by cristianpb** [comment]
Hello @skeggse 

Just to let you know that this is not in the release v1.2.3 (28/01/2020)

https://github.com/bee-queue/bee-queue/blob/v1.2.3/index.d.ts#L79

The modifications has been taken into account after that (14/04/2020)

https://github.com/bee-queue/bee-queue/commit/bc8aa522f66ed7038bdea03629c0f3244ea8a55f
