### ISSUE TITLE
Job is stalled but isn't being reprocessed

### ISSUE THREAD

**Issue by divmgl** [bee-queue/bee-queue#120]
I'm having an issue where a job is getting repeatedly stalled using `checkStalledJobs` but isn't being reprocessed. The `stalled` event is fired, but none of the workers processing events receive the job again. Is there a specific thing I need to do to make the workers receive stalled jobs?

**Comment by LewisJEllis** [comment]
Hmm, if you're calling `checkStalledJobs` periodically that should be all you need. Could you provide an example so I can try to reproduce?

**Comment by divmgl** [comment]
Already switched. Unfortunately the task I was working on is time sensitive. If it comes up again in a future project I'll try to reproduce.
