### ISSUE TITLE
How do I report a job failure when using a handler function with async/await?

### ISSUE THREAD

**Issue by josephchan91** [bee-queue/bee-queue#122]
Do I just throw an error like this?
```
addQueue.process(async (job) => {
  const requiredParameter = await db.getRequiredParameter(job.id);
  if (!requiredParameter) {
    throw new Error("Job failed because required parameter is missing.")
  }
  return requiredParamter;
});
```

**Comment by guanMac** [comment]
you can code like this
`
addQueue.process(async (job) => {
  const requiredParameter = await db.getRequiredParameter(job.id);
  if (!requiredParameter) {
    return Promise.reject();
  }
  return requiredParamter;
});
`

**Comment by dealslama** [comment]
How do i re-create the job which is failed.. I tried setting the retries but I want to resubmit the job when I get the timeout event

**Comment by skeggse** [comment]
@guanMac's code will do the trick, and so will your original code, @josephchan91. Note that you may want to distinguish between _transient_ failures (e.g. connection errors & timeouts) and _permanent_ failures (e.g. malformed input). In the former case, you'd want to retry the job, but in the latter case you'd want to log the failure and permanently abort the job. How you handle these cases is up to you as a user of this library, but note that if you configure `retries` and `throw`/`reject` in the job handler, it'll [always retry](https://github.com/bee-queue/bee-queue/blob/c92207e946a50056227a214444fa3405f57433da/lib/queue.js#L541) the job.

I'm closing this issue as I think I've answered your question, but feel free to clarify!

@dealslama please open a new issue with your question.
