### ISSUE TITLE
Distributed job management

### ISSUE THREAD

**Issue by dealslama** [bee-queue/bee-queue#124]
I'm using beeQueue for video transcoding job scheduling and processing

For now everything is fine and but I'm now facing challenge of working with distributed environment like auto scaling the amazon the instances for adding more workers to process more jobs which are pending in the queue, We scale well but need to implement a system which is fail safe, I mean in case a instance on which workers were processing the job has gone shutdown and we don't get job status or events, In that case the job which were running on that instance is gone into blackhole and can't be recovered and processed again.

**Comment by skeggse** [comment]
Hi, thanks for using bee-queue! I'm not entirely clear on what your question is, and how bee-queue falls short for your use-case. Can you say more?

**Comment by gwl002** [comment]
I am also interested in this question.If I have two workers,worker1 and worker2 share the same redisClient,If worker1 has processed job A and failed,can worker2 get the status of job A?Can job A be processed by worker2 in the retrys.

**Comment by skeggse** [comment]
Hi @gwl002 - your question seems unrelated to @dealslama's question. Please open a new issue! The short of it, as I understand your question, is yes: two instances of bee-queue can share a redis connection, but will open extra connections for blocking job acquisition operations.

**Comment by dealslama** [comment]
@skeggse Thanks for reply,
I've 3 instances, one for pushing jobs into redis Q, other two are just running workers, 
but the other workers instances could not fetch /  process job from redis even they are sharing the same redis host,

Also My primary question was if from two of other instances one gets shutdown / crash would the other instance will pick up the stalled jobs which left orphan by dead instance ? 

Any idea what is missing?

Thanks
Ravi

**Comment by dealslama** [comment]
@skeggse Does this module support redis cluster ?

**Comment by skeggse** [comment]
>My primary question was if from two of other instances one gets shutdown / crash would the other instance will pick up the stalled jobs which left orphan by dead instance ?

Yep! If that's not happening for you, double-check that you're calling `Queue#checkStalledJobs`. I think we need better documentation on that - tracked in https://github.com/bee-queue/bee-queue/issues/170.

>Does this module support redis cluster ?

Not yet. That'll be available in #112.
