### ISSUE TITLE
Writing a consumer in another language

### ISSUE THREAD

**Issue by sharksforarms** [bee-queue/bee-queue#126]
Hello, I'd like to use your library for the purpose of "A web server can enqueue a job, wait for a worker process to complete it, and return its results within an HTTP request."

But my task consumers are not written in Node. Is there an API specified anywhere I can reference to consume and reply to tasks? Thanks.

**Comment by dylanjha** [comment]
For a solution that works across different languages you might want to have a look at faktory: https://github.com/contribsys/faktory

I haven't used it myself but it seems like having language-agnostic producers and consumers is one of the core principles of the project.

**Comment by skeggse** [comment]
>Is there an API specified anywhere I can reference to consume and reply to tasks?

Nope! That'd be a great addition, however :)
