### ISSUE TITLE
Consumer can't process jobs

### ISSUE THREAD

**Issue by dealslama** [bee-queue/bee-queue#127]
Hello,
I've a one producer instance on amazon ec2
const ffmpegQ = new Queue('FFMPEG',{
  prefix: 'bq',
  stallInterval: 3000,
  nearTermWindow: 5000,
  delayedDebounce: 1000,
  redis: config_object,
  isWorker: true,
  getEvents: true,
  sendEvents: true,
  storeJobs: true,
  ensureScripts: true,
  activateDelayedJobs: true,
  removeOnSuccess: true,
  removeOnFailure: true,
  redisScanCount: 100
});

and 4 workers using pm2 module on another instance:

const ffmpegQ = new Queue('FFMPEG',{
  prefix: 'bq',
  stallInterval: 3000,
  nearTermWindow: 5000,
  delayedDebounce: 1000,
  redis: config.redis.primary,
  isWorker: true,
  getEvents: true,
  sendEvents: true,
  storeJobs: true,
  ensureScripts: true,
  activateDelayedJobs: true,
  removeOnSuccess: true,
  removeOnFailure: true,
  redisScanCount: 100
});

ffmpegQ.process(config.ffmpeg.concorrency,function (job, done) {
  log.info('Processing JOB ',job.data);
  util.dpTranscode(job.data.cmd,done,job);
});

Producers are putting job in redis that i can check on arena-bull, but they all are in waiting status

Redis connection is same for both producer and consumer and there is no error in connection ? 

Am I missing something ? Can someone point me in right direction ?

**Comment by dealslama** [comment]
Issue 1 : Workers are accessing the locally installed Redis even after providing the redis client object.

**Comment by dealslama** [comment]
The problem was redis connection I thought I'm connected to shared redis but I didnt worked
I;ve a redis cluster and object is like : 
[{
      "port": 6379,
      "host": "10.100.40.68"
    },{
      "port": 6379,
      "host": "10.100.40.73"
    },{
      "port": 6379,
      "host": "10.100.40.40"
    }]

I passed it to redis option in the Q config.

How I can pass this redis cluster object ?

**Comment by dealslama** [comment]
Does this Q support redis cluster ?

**Comment by skeggse** [comment]
> Does this Q support redis cluster ?

We will once we have `ioredis` in #112.
