### ISSUE TITLE
jobs are not cleared under high load

### ISSUE THREAD

**Issue by sharonass** [bee-queue/bee-queue#129]
Hello,

I use bee-queue in production with a high load  - our production gets milions of impressions per day and for some of them we need to do some job, thus I use the queue with the following config:
        storeJobs: false,
        removeOnSuccess: true,
        removeOnFailure: true,

and I'm pushing jobs 

const job =  myQueue.createJob(projectData);
        job.setId(customId);
        let saved_job = await job.save();

Our scenario implies that there might be large amount (up to few thousands in few seconds) of jobs with the same customId coming in parallel, and I use the queue functionality that there cannot be more than one job with same id on the queue on the same time while waiting for worker to take it as a backfire mechanism to prevent dupicated jobs on the same time, I dont have a problem to accept another job with same Id after one of my workers took it from the queue.

This works well for few weeks now up untill last week when our load increased by ~50% than I started to see that   job.save(); retuned job id = null meaning it stopped inserting new jobs to the queue.

looking at Arena didnt show any problem all the queue in areana (waiting, failed, success, etc) looked ok, but no jobs where going into the queue anymore.

After debugging it and going deep into the internal queue I found the problem.

I saw that there are many jobs "stuck" in your internal queue  bq:name:jobs (~ 40k)  and that prevented fmost of jobs with same id to get in.

only after deleting bq:name:jobs  directly from redis the system returned to work normally and I saw that bq:name:jobs  is being cleaned

Please advise how to prevent this from hapenning again

Thanks in advance
-sharon

**Comment by skeggse** [comment]
We handle a sustained ~3k jobs per second in a single queue, and it's kept up with that load for months.

>I saw that there are many jobs "stuck" in your internal queue bq:name:jobs (~ 40k) and that prevented fmost of jobs with same id to get in.

This is likely the culprit. If you have a job with a given ID in the queue, and try to create a new job with the same ID, then the job does not get created. It sounds like your `customId` may have duplicates. Why do you use a custom job ID? The primary use-case for custom job IDs is to enable a singleton delayed job.

**Comment by skeggse** [comment]
As this issue is more of a question, and doesn't include an MCVE, I'm closing this. Feel free to re-open if you think there is an actual error in bee-queue, and feel free to comment if you have more questions.
