### ISSUE TITLE
Consumer stops consuming if job returns circular result

### ISSUE THREAD

**Issue by hhhonzik** [bee-queue/bee-queue#136]
We successfully use bee-queue for communication between our node apps and found an issue when updating our logging library, which send circular object as a result by accident.

Minimal example can be this:

```
const Queue = require('bee-queue');
const queue = new Queue('example');

const job = queue.createJob({x: 2, y: 3})
job.save();
job.on('succeeded', (result) => {
  console.log(`Received result for job ${job.id}: ${result}`);
});

// Process jobs from as many servers or processes as you like
queue.process(function (job, done) {
  console.log(`Processing job ${job.id}`);

  const circularResult = {
    x: job.data.x,
    y: circularResult
  };
  return done(null, circularResult);
});
```

The job won't move from active state, it gets properly marked as "stalled", but the queue is stuck and don't process any more tasks.

The line that causes an error is here: 
https://github.com/bee-queue/bee-queue/blob/v1.2.2/lib/queue.js#L564

We fixed the issue in our code (we make sure no circular JSON is sent as result), but I think this could be handled better by bee-queue. I suggest add `try / catch` over those lines, move it to a promise or at least log it as queue error. Happy to do a PR if we get anywhere with this.

**Comment by skeggse** [comment]
I think the minimal example you provided isn't quite demonstrating the issue you're seeing. The following snippet won't work without an existing `circularResult` binding in an ancestor scope.

```js
const circularResult = {
  x: job.data.x,
  y: circularResult
};
```

However, I can imagine code that does create a circular result and attempts to reply with it.

How do you think that case should be handled? Would this qualify as a job failure, worthy of causing the job to retry? Perhaps a special kind of job failure that bypasses the retry mechanism? Just a Queue `error` event?

**Comment by hughsw** [comment]
I vote for the special Queue `error` event.  Docs for `Queue#process` should be update to mention that circular results are not supported and will result in a failure that won't be retried.

**Comment by billyen2012** [comment]
This issue should be closed.  Not a bug. 

Failed job need to be handle in the `on('failed')` event (either in job level with `job.on("failed", (err)=>{})`, or in queue level with `queue.on('failed', (job, err)=>{})` )
