### ISSUE TITLE
Doesn't start on launch?

### ISSUE THREAD

**Issue by luminous8** [bee-queue/bee-queue#137]
Hey guys,

When I'm starting my queue it happen sometimes that there is some failed jobs but the queue doesn't treat them.
<img width="646" alt="capture d ecran 2018-08-11 a 22 10 14" src="https://user-images.githubusercontent.com/17875165/43995722-92f04966-9db3-11e8-91e2-0627d7923f0b.png">

Is there anything to do, to launch them manually?

Thanks

**Comment by luminous8** [comment]
FYI here's my config 
`
    "isWorker": true,
    "removeOnSuccess": true,
    "removeOnFailure": false,
    "stallInterval": 360000,
    "ensureScripts": true,
    "maxConcurrencyJobs": 10
  `

**Comment by skeggse** [comment]
Jobs that have `failed` will never be retried. You'll need to use the `Job#retries` and `Job#backoff` options to control what happens before they fail fatally. It sounds like you might benefit from a job management tool like [Arena](https://github.com/bee-queue/arena)!
