### ISSUE TITLE
Repeat job?

### ISSUE THREAD

**Issue by ChrisRobston** [bee-queue/bee-queue#139]
Hi. Is this possible to achieve repeatable job? Let's say to run a job every 5 minutes.

**Comment by kirito1121** [comment]
You can create a task run every 5 minutes and write job in that.

**Comment by skeggse** [comment]
Repeatable jobs aren't an explicitly supported feature of `bee-queue`. We might be willing to consider a pull-request, but it has rather deep implications for a bunch of assumptions we make about unidirectional state transitions.

@kirito1121 is right about being able to chain jobs off of each other.

**Comment by Gaen** [comment]
At first I've tried `job.delayUntil(nextTime).save` just inside `process` handler. It kinda worked but my queue kept saying that the job is detected as stalled. Looks like modifying the job while it is still being processed is not such a good idea (:

So I've come up with a workaround like this one instead:

```js
const MY_JOB_ID = 'hello-world';

queue.process(async job => {

  // do some work
  await new Promise(resolve => setTimeout(resolve, 1000));

  // explicitly get job in order to receive its events
  const self = await queue.getJob(MY_JOB_ID);

  // reschedule on success
  self.once('succeeded', () => queue.createJob().setId(MY_JOB_ID).delayUntil(Date.now() + 10000).save());

});

// check if job is present
const job = await queue.getJob(MY_JOB_ID);

// create if not
if(!job)
  await queue.createJob().setId(MY_JOB_ID).save();
```
Here the new job (with the same id) is created _after_ the old one is succeeded and removed (`removeOnSuccess: true`). Works for me good enough for now.
