### ISSUE TITLE
Concurrency and order across queues?

### ISSUE THREAD

**Issue by Vortec4800** [bee-queue/bee-queue#141]
I have a bunch of different job types, so they would each get a separate queue, however each job is scheduled in a particular order. For example, there are a bunch of jobs that run that calculate points for users, then once those jobs complete I've got another job scheduled that sends out score notifications.

Can I do this using Bee? It seems like if I create 1000 calculation jobs and 1 notification job across 2 queues, my notification job would likely run before the calculation jobs are all complete.

**Comment by skeggse** [comment]
We don't explicitly support this kind of inter-job dependency. Your best bet might be to create the job on-demand when the last job completes. I could see an argument for this being included as a plugin.

**Comment by hughsw** [comment]
Inter-job dependency is a rich topic.  Some systems I've worked with, e.g. [Drone](https://drone.io/), let each job specify a list of parent jobs that have to have succeeded before the job itself starts.  This is a very simple approach to setting up a dependency DAG. 

This would not be particularly difficult to implement in a layer using the Bee-Queue API.  As @skeggse says, perhaps a plugin....
