### ISSUE TITLE
Not checking if EXISTS before querying key causeing keyspace_missing hit

### ISSUE THREAD

**Issue by jbool24** [bee-queue/bee-queue#142]
Preloaded Lua scripts run calls to Redis without first checking if the keys exist on `bq:[queue_name]:stalling` and `bq:[queue_name]:waiting` which causes keyspace_misses to increase in multiples (see below) according to each Queue instance created. There is a case when there are no jobs in the Queue instance so those keys will not exist in Redis at the time the script is run causing the unnecessary miss and subsequent counter increment.

Scripts involved:
1. addDelayedJob.lua (4x per queue instance)
2. raiseDelayedJobs.lua (2x per queue instance)

**Comment by skeggse** [comment]
I'm not familiar with `keyspace_missing` - what's the origin of that name? If I understand the concern correct, it sounds like it's a surface-level metric. I can't imagine that calling an `LREM` on a non-existent key is very expensive, and it seems like calling `EXISTS` would just slow down the normal case.

**Comment by hughsw** [comment]
Is this a Redis/Lua linting concern?  Or, as per @skeggse , a hard-to-imagine performance issue?

**Comment by jbool24** [comment]
This was opened sooooo long ago I no longer remember the context unfortunately. I won't be able to add any insight as I'm no longer on the project that brought this to my attention and asked to open this issue. For this reason I will close this issue.
