### ISSUE TITLE
How can we minimize the number of redis connections used by bee-queue?

### ISSUE THREAD

**Issue by rj-david** [bee-queue/bee-queue#144]
I am currently using redis labs which currently sets the limit of connections to the redis server.

I have 3 redis database and one of those is being used by bee-queue. The database by bee-queue registers a lot of connection. Currently, it records 69 connections and it continue to increase as new jobs are created and executed by bee-queue. My redis server has a limit of 256 connection.

My other databases for comparison: app database consistent 6 connections; redis oplog database consistent at 12 connections.

Only the bee-queue uses a lot of connections and it is increasing. How can we keep the number of connections low? Is there any settings required for a connection pool?

**Comment by samuelgoldenbaum** [comment]
no reply since Sep 7?

**Comment by lbtuda** [comment]
Any updates on this?

**Comment by amrshakya** [comment]
Any Update on this?

**Comment by amrshakya** [comment]
@rj-david Hi did you find any solution for this? I'm also facing the same problem bee-queue using too many redis connection. How can we minimize it or release the connection if not in use.
@LewisJEllis  Please help on this.

**Comment by bradvogel** [comment]
Does this section help explain: https://github.com/bee-queue/bee-queue#optimizing-redis-connections ? There's a new connection per `new Queue` (since each queue needs to run a blocking redis command).

**Comment by rj-david** [comment]
We managed the connections outside of beequeue. But our requirements outgrew the capabilities of beequeue so we moved to bull as our queue manager

**Comment by skeggse** [comment]
If anyone in this thread still has an issue that isn't solved by the [Optimizing Redis Connections](https://github.com/bee-queue/bee-queue#optimizing-redis-connections) section, please open a new issue.
