### ISSUE TITLE
How to slow down job execution 

### ISSUE THREAD

**Issue by csakis** [bee-queue/bee-queue#145]
I am trying to fill up a database table with data using bee-queue. I would like to throttle the execution of the putItem commands, so that I don't overwhelm the server. No matter how I set the delayedDebounce or other timing settings on the queue, the jobs are processed as fast as they can. Is there a simple way to set a delay on job processing?

**Comment by skeggse** [comment]
You could have each job wait before resolving - artificially increasing the time each job takes while holding the concurrency constant should result in a lower overall job throughput.

**Comment by jcs224** [comment]
Most obvious use case to me is an easy way to throttle how often you can hit an external API that has limits on how often it can be hit from the same IP address. For example, Vultr's API only allows 30 per second.

https://www.vultr.com/api/#:~:text=Rate%20Limit:%20Vultr%20safeguards%20the,return%20HTTP%20status%20code%20503.
