### ISSUE TITLE
Global concurrency limit for all queues

### ISSUE THREAD

**Issue by iNDicat0r** [bee-queue/bee-queue#148]
The problem is that each job queue.process has its own concurrency mechanism. My design requires a global concurrency limit, so multiple queues follow the global limit.

e.g.: 100 job queues => 10 concurrent request

There is a workaround, to implement everything in one queue and handle the job type/function at that level but I find it a bit messy.

**Comment by cymen** [comment]
You could use a rate limiter like [bottleneck](https://www.npmjs.com/package/bottleneck) with the options set to store the limiter in redis. Then you can reuse that limiter in each queue that should be part of the global concurrency limit. I do this to share limits between some workers for an external API that I hit. Here is my limiter:

```javascript
import Bottleneck from 'bottleneck';

const limiter = new Bottleneck({
  id: 'my_global_limiter',
  datastore: 'redis',
  clearDatastore: false,
  clientOptions: {
    host: '127.0.0.1',
    port: 6379,
  },
  maxConcurrent: 10,
  /*
  // my external API actually allows X calls per second so I'd set something like below too
  reservoir: 10,
  reservoirRefreshAmount: 10,
  reservoirRefreshInterval: 10,
  expiration: 60000,
  */
});

export default limiter;
```

Then just import that anywhere you need it and use it per the Bottleneck docs. As an example:

```javascript
...
queue.on('ready', () => {
  queue.process(async (job, done) => {
    await limiter.schedule(async () => {
...
```

**Comment by cymen** [comment]
Forgot one thing, it might be best to reverse the usage of the limiter in the queue to something more like:

```javascript
...
queue.on('ready', () => {
  await limiter.schedule(async () => {
    queue.process(async job => { 
...
```
That way, in say a multiple worker situation, the job isn't taken until the limiter gives the okay. I am going to try this soon (using the prior example approach at the moment).

**Comment by iNDicat0r** [comment]
@cymen thanks for the info, I basically implemented a limiter which does what Bottleneck does:) I will refactor to support Bottleneck!

**Comment by NavpreetDevpuri** [comment]
@cymen  I have 3 node processes running with the following code and It is still taking jobs concurrently, I want one job to finish before any other worker takes the next job.

```js
// worker queues running on the worker server
const Bottleneck = require('bottleneck').default;

const limiter = new Bottleneck({
  id: 'my_global_limiter',
  datastore: 'redis',
  clearDatastore: false,
  clientOptions: {
    host: '127.0.0.1',
    port: 6379,
  },
  maxConcurrent: 1,
  /*
  // my external API actually allows X calls per second so I'd set something like below too
  reservoir: 10,
  reservoirRefreshAmount: 10,
  reservoirRefreshInterval: 1000,
  expiration: 60000,
  */
});

const Queue = require('bee-queue');
const redis = require('redis');
const redisClient = redis.createClient({ url: 'redis://127.0.0.1:6379' });
redisClient.on('connect', function () {
  console.log('redis connected');
});
redisClient.on('error', function (error) {
  console.log(error);
});
// redisClient.connect();

const sharedConfig1 = {
  redis: redisClient,
  isWorker: true,
};

const emailQueue1 = new Queue('EMAIL_DELIVERY', sharedConfig1);
emailQueue1.getJobs('failed', { size: 100 }).then((jobs) => {
  const jobIds = jobs.map((job) => job.id);
  console.log(`Job ids: ${jobIds.join(' ')}`);
});

emailQueue1.on('ready', async () => {
  emailQueue1.process(async (job) => {
    await limiter.schedule(async () => {
      console.log('#### Works', job.data.a, job.id);
      await new Promise((r) => setTimeout(r, 3000));
    });
  });
});

```

**Comment by NavpreetDevpuri** [comment]
I found an alternative solution to my problem by using [redis-ordered-queue](https://www.npmjs.com/package/redis-ordered-queue)
