### ISSUE TITLE
Question: to handle a long background jobs, should I use  callback or promise version handler ?

### ISSUE THREAD

**Issue by qiulang** [bee-queue/bee-queue#151]
Hi,
This is a question.  All my tasks are long background jobs, downloading files most of time. So does it make any difference to use callback version of promise version of task handler ?  Once the task is started,  I only care about whether it succeeds or fails.

`queue.process((job, done) => {...}) or queue.process(async (job) => {...})`

Thanks!

**Comment by dylanjha** [comment]
@qiulang I don't believe there is any difference for your use case

**Comment by qiulang** [comment]
OK thanks
