### ISSUE TITLE
Get queue by name

### ISSUE THREAD

**Issue by tab00** [bee-queue/bee-queue#152]
My app needs multiple queues so I want to be able to access one by using the queue name (as a queue ID). e.g.:

```js
const queueId = `queue-${var1}-${var2}`
let queue = getQueue(queueId)
if (queue === undefined) queue = new Queue(queueId, { })
```

Can this be possible?

**Comment by mvhirsch** [comment]
Of course this is possible. Just use a `Map` (or an Object, or an Array) for holding them:

```
const queues = new WeakMap();

const queueId = `queue-${var1}-${var2}`
if (!queues.has(queueId)) {
  queues.set(queueId, new Queue(queueId, {});
}

const queue = queues.get(queueId);
```

**Comment by skeggse** [comment]
You can construct `Queue` objects however you like. The core `bee-queue` library does not directly support managing multiple queues, but doesn't prevent you from doing so either!
