### ISSUE TITLE
Event for Job queued

### ISSUE THREAD

**Issue by maikelmclauflin** [bee-queue/bee-queue#159]
hi there. thanks for the package. just had a quick question. is there a [job event](https://github.com/bee-queue/bee-queue#job-events) like the queue's `ready` that signifies it was successfully queued? i want to be able to have the behavior of, "i don't care who takes care of the job / when. just let me know that you put it on redis"

**Comment by batuhandirek** [comment]
I think job.save() method succeeding means the job is on Redis, otherwise it will throw an error.

**Comment by skeggse** [comment]
Yep! When `Job#save` completes, you can be confident that the job was persisted to Redis.
