### ISSUE TITLE
is there any way to mark a job as completed outside the process handler ?

### ISSUE THREAD

**Issue by Mouhssine** [bee-queue/bee-queue#160]
Hello guys , im using bee-queue for doing some intensive crawling using several servers running bee-queue and i had like to ask if there's a way to mark a job as "done" outside the process function handler and after marking it as completed the process move to next job ... 
not sure if this is realistic lol .

Thanks !

**Comment by skeggse** [comment]
This isn't currently supported, and it seems like you're looking for a job storage/tracking engine rather than a job queue. `bee-queue` is pretty hyperfocused on supporting workflows where the work for a job happens in one place in a time-bounded manner.
