### ISSUE TITLE
Why bee-queue?

### ISSUE THREAD

**Issue by aymericbouzy** [bee-queue/bee-queue#161]
I've read https://github.com/bee-queue/bee-queue/wiki/Origin but I still don't understand why you would need to go through running a job in a queue if you need to send the results in the response. If I was facing this situation, I would simply run the code in the request, without going through a job. I'd be glad to have a real world example to understand why you would need this architecture. Thanks!

**Comment by bradvogel** [comment]
A distributed queue is a useful tool for building software at scale. Work can be distributed across many computers (instances) and the queue ensures that each instance doesn't get overloaded (ie processing too many jobs at once).

For example, at Mixmax, we handle bursts of 15M inbound requests a second. Without a queue, the server would quickly fall over. With Bee Queue, 15M jobs are created and then processed by a fleet of 20+ instances over time.

**Comment by aymericbouzy** [comment]
Thanks for the response!
