### ISSUE TITLE
Job Backoff does not work

### ISSUE THREAD

**Issue by CHOMNANP** [bee-queue/bee-queue#164]
I run this source code.But the job retries does not work when we enable "backoff".
Any tips on how to get it working?

````
const Queue = require('bee-queue');
const queue = new Queue('Transfer');

async function init() {
    const job = await queue.createJob({
        activateDelayedJobs: true
    });
    job.retries(5)
    job.backoff("fixed", 100)
    job.save()

}

queue.on('Transfer succeeded', (jobId, result) => {
    console.log(`Job ${jobId} succeeded with result: ${result}`);
});

init();
// for (let i = 0; i < 10000; i++) {
//     queue.createJob({ x: 2, y: 3 }).save();
// }

queue.process(5000, async function (job, done) {
    console.log(`Processing job ${job.id} `, job.options.backoff);
    // return done(null, job.data.x + job.data.y);
    throw 'This is failed';
});
````

**Comment by vinarmani** [comment]
I am having the same issues, with the same settings.

**Comment by skeggse** [comment]
Job backoff is known to work - we use it in production every day. I believe @vinarmani is correct in that you have to pass `activateDelayedJobs` as a parameter to the `Queue` constructor instead of in the data parameter of the `createJob` function. If you're still encountering trouble, let us know!
