### ISSUE TITLE
Priority Job support like kue

### ISSUE THREAD

**Issue by MrSpark2591** [bee-queue/bee-queue#167]
Great package guys! We are using this one in production.
But for some modules we want feature of priority job same as kue supports. Is there any road map to it or Let me know if i can be helpful for the implementation.

**Comment by manast** [comment]
You can use https://github.com/optimalbits/bull for priority support and many more.

**Comment by skeggse** [comment]
This is not currently supported, and is [not on the roadmap](https://github.com/bee-queue/bee-queue#contributing). We might consider a PR to add this functionality. We're currently considering adding a plugin system to support this kind of non-core use-case.
