### ISSUE TITLE
Why jobs are getting stuck while redis disconnects on some of the workers?

### ISSUE THREAD

**Issue by dave7280** [bee-queue/bee-queue#170]
HI,

I recently started using bee-queue and encountered a problem, while i was running my solution over night. I had around 40 workers spawned and logging enabled. During night we had some redis connection problems which resulted in following exception on some of the workers. As result few workers died and stopped processing. This resulted in 1200 of orphaned jobs in "active " state.

```
[2019-07-21 01:59:03] error: uncaughtException: Redis connection to 95.179.XXX.XXX:6379 failed - read ETIMEDOUT
Error: Redis connection to 95.179.XXX.XXX:6379 failed - read ETIMEDOUT
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)

Also information from console:

node:3638) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 288)
(node:3638) UnhandledPromiseRejectionWarning: AbortError: Redis connection lost and command aborted. It might have been processed.
    at RedisClient.flush_and_error (/root/node_modules/redis/index.js:362:23)
    at RedisClient.connection_gone (/root/node_modules/redis/index.js:664:14)
    at Socket.<anonymous> (/root/node_modules/redis/index.js:289:14)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:567:12)
````

Redis data:
bq:QUEUENAME:active -> 1200 elements
bq:QUEUENAME:jobs -> 1200 elements where each one has "created" status with info below

```
{"data":{"ourdata":"someofourmaskeddata"},"options":{"timestamp":1563691203257,"stacktraces":[],"timeout":180000,"retries":0},"status":"created"}
```

After that event:
- I have 1200 jobs in "active" state that are hanging on redis, even though stalled jobs monitoring is enabled and was working correctly in "testing" phase while killing and restarting worker. These jobs are not being processed and are stuck there from the moment redis connection was lost.
- Some workers have died as this exception triggered.

Questions.

1. Does bee-queue handle redis re-connection? Can we enable such function?

2. Why do active jobs that were "left" by workers which died as result of redis disconenction are not being retried by other workers that are alive? (Stalled jobs monitoring)
Especially that once we were inserting jobs, they were getting processed (meaning we had still some of the workers alive), they just didnt process stalled jobs.

3. After i killed entire worker cluster and re-started it, the 1200 stuck "active" jobs were correctly processed. Why was killing entire cluster of node processes necessary to re-process these jobs?

**Comment by skeggse** [comment]
>Does bee-queue handle redis re-connection? Can we enable such function?

We mostly rely on node_redis' reconnection functionality. For the most part, we don't have carefully designed recovery functionality - if an operation fails due to network problems, it may or may not have completed, and you'll likely need to manually retry it. I do see an argument for more rigorous testing on that front.

As far as stuck jobs go, you should double-check that you're calling `Queue#checkStalledJobs` with an `interval` so that it discovers and re-enqueues stuck jobs. We might decide that this should start by default, but that prompts the question about how to handle failures - do we just `emit` them? It might also be worth clarifying the documentation on this point.

>After i killed entire worker cluster and re-started it, the 1200 stuck "active" jobs were correctly processed. Why was killing entire cluster of node processes necessary to re-process these jobs?

When a worker starts, it checks for stalled jobs once (via the `Queue#process` call). Starting a worker would have discovered the stalled jobs and started processing them again.

**Comment by hudsonfr** [comment]
The same thing is also happening to us!! Do you have any results?

**Comment by skeggse** [comment]
I believe I addressed the original questions in my comment above. I haven't heard back, so I'll close this issue. @hudsonfr - if you have a specific bug to report, please open a new ticket with details!
