### ISSUE TITLE
workers with activateDelayedJobs without getEvents

### ISSUE THREAD

**Issue by gask** [bee-queue/bee-queue#176]
Hi there, today I run into a problem and got really confused, tried finding something in your docs but didn't find anything that could help me.
The situation is basically this:

I have a worker that needs to have the **activateDelayedJobs** feature on but doesn't necessarily receives any event. To avoid many client connections, I'm doing a queue cleanup every now and then: At first, the option **activateDelayedJobs** was off and it was working perfectly, the queues and all their connections were properly closed. But when I turned on **activateDelayedJobs** suddenly SUBSCRIBE connections were not closing. BRPOPLPUSH and EXEC were normally being closed, but the SUBSCRIBE connection didn't go away.

Running through your Queue class code I could find inside the close function code this part:

      const cleanup = () => {
            this._isClosed = true;

            const clients = [];
            if (this.settings.quitCommandClient) {
              clients.push(this.client);
            }
            if (this.settings.getEvents) {
              clients.push(this.eclient);
            }

            return Promise.all(clients.map((client) => {
              const promise = helpers.deferred();
              client.quit(promise.defer());
              return promise;
            }));
      };

The check for the **getClients** setting gave me the hint that the client was only being cleaned if this was also on. So when I turned it on in my queue, the connections started to clean properly upon close() call.

I don't know if this is a bug or if this is intended to happen. If this behaviour is intended, then it should be on the docs that if you turn off the **getClients** setting and **activateDelayedJobs** as well, your close calls will not happen properly.

**Comment by skeggse** [comment]
I believe this was fixed in #178. Let me know if that's not the case!
