### ISSUE TITLE
How can I reject a job?

### ISSUE THREAD

**Issue by phenrigomes** [bee-queue/bee-queue#177]
If I enqueue a job I need to reject it if I have another worker processing or pending to process it. How can I get that? Thanks!

**Comment by hughsw** [comment]
I'm not sure what Issue you are reporting.  

Once the `job.save()` promise has resolved (job is enqueued), you cannot deterministically stop it. 

You can call `job.remove()`, but it's behavior is only mildly guaranteed (idempotency): https://github.com/bee-queue/bee-queue#jobremovecb

You can also call `queue.removeJob(jobId, [cb])`.  It too has only mild guarantees:  https://github.com/bee-queue/bee-queue#queueremovejobjobid-cb
