### ISSUE TITLE
Job stuck when worker SIGINTs

### ISSUE THREAD

**Issue by miguel-guedes** [bee-queue/bee-queue#181]
### Synopsis

A job becomes stuck when a worker that begins processing it terminates abruptly; e.g. via <kbd>CTRL</kbd>-<kbd>C</kbd>. Running the worker after termination does not cause the job to be restarted immediately; instead, this happens randomly and requires multiple restarts of the worker instance.

### How to reproduce
1. Create the following source files:

**server.js**
```js
const Queue = require("bee-queue");
const queue = new Queue("test");
const job = queue.createJob({ timestamp: Date.now() });
job.save().then(() => {
  console.log("job created");
  process.exit(0);
});
```

**worker.js**
```js
const Queue = require("bee-queue");
const queue = new Queue("test");
const timeout = +process.argv[2];
queue.process(job => {
  console.log("processing job:", job.id);
  return new Promise(r => {
    if (!isNaN(timeout)) {
      console.log("concluding job:", job.id);
      setTimeout(r, timeout);
    }
  });
});
```

**status.js**
```js
const Queue = require("bee-queue");

let queue = new Queue("test", {
  activateDelayedJobs: true,
});

queue.on("job succeeded", id => console.log("job succeded:", id));
queue.on("job failed", id => console.log("job failed:", id));
queue.on("job retrying", id => console.log("job retrying:", id));


async function printStatus() {
  console.log(await queue.checkHealth());
}

printStatus().then(() => process.exit(0));
```

2. Run `node server.js` to create a job
3. Run `node worker.js` to begin processing the job
4. Interrupt the worker with <kbd>CTRL</kbd>-<kbd>C</kbd>
5. Run `node status.js` and goto 4 until the job finally restarts.

### Example run
```
$ node server.js
job created
$ node worker.js 
processing job: 1
^C
$ node worker.js 
^C
$ node worker.js 
^C
$ node worker.js 
^C
$ node worker.js 
^C
$ node worker.js 
^C
$ node worker.js 
^C
$ node worker.js 
^C
$ node status.js
{
  waiting: 0,
  active: 1,
  succeeded: 0,
  failed: 0,
  delayed: 0,
  newestJob: 1
}
$ ^C
$ node worker.js 
processing job: 1
^C
$ node worker.js 1000
^C
$ node worker.js 1000
^C
$ node worker.js 1000
^C
$ node worker.js 1000
^C
$ node worker.js 1000
^C
$ node worker.js 1000
processing job: 1
concluding job: 1

^C
$ node status.js
{
  waiting: 0,
  active: 0,
  succeeded: 1,
  failed: 0,
  delayed: 0,
  newestJob: 1
}
$
```

### Questions
1. Why is the job not restarted immediately when the worker is instantiated after it has been terminated?

**Comment by s888** [comment]
> ### Synopsis
> 
> A job becomes stuck when a worker that begins processing it terminates abruptly; e.g. via CTRL-C. Running the worker after termination does not cause the job to be restarted immediately; instead, this happens randomly and requires multiple restarts of the worker instance.
> ### How to reproduce
> 
>     1. Create the following source files:
> 
> 
> **server.js**
> 
> ```js
> const Queue = require("bee-queue");
> const queue = new Queue("test");
> const job = queue.createJob({ timestamp: Date.now() });
> job.save().then(() => {
>   console.log("job created");
>   process.exit(0);
> });
> ```
> 
> **worker.js**
> 
> ```js
> const Queue = require("bee-queue");
> const queue = new Queue("test");
> const timeout = +process.argv[2];
> queue.process(job => {
>   console.log("processing job:", job.id);
>   return new Promise(r => {
>     if (!isNaN(timeout)) {
>       console.log("concluding job:", job.id);
>       setTimeout(r, timeout);
>     }
>   });
> });
> ```
> 
> **status.js**
> 
> ```js
> const Queue = require("bee-queue");
> 
> let queue = new Queue("test", {
>   activateDelayedJobs: true,
> });
> 
> queue.on("job succeeded", id => console.log("job succeded:", id));
> queue.on("job failed", id => console.log("job failed:", id));
> queue.on("job retrying", id => console.log("job retrying:", id));
> 
> 
> async function printStatus() {
>   console.log(await queue.checkHealth());
> }
> 
> printStatus().then(() => process.exit(0));
> ```
> 
>     1. Run `node server.js` to create a job
> 
>     2. Run `node worker.js` to begin processing the job
> 
>     3. Interrupt the worker with CTRL-C
> 
>     4. Run `node status.js` and notice how the job is both waiting and active.
> 
> 
> ### Example run
> 
> ```
> $ node server.js
> job created
> $ node worker.js 
> processing job: 1
> ^C
> $ node worker.js 
> ^C
> $ node worker.js 
> ^C
> $ node worker.js 
> ^C
> $ node worker.js 
> ^C
> $ node worker.js 
> ^C
> $ node worker.js 
> ^C
> $ node worker.js 
> ^C
> $ node status.js
> {
>   waiting: 0,
>   active: 1,
>   succeeded: 0,
>   failed: 0,
>   delayed: 0,
>   newestJob: 1
> }
> $ ^C
> $ node worker.js 
> processing job: 1
> ^C
> $ node worker.js 1000
> ^C
> $ node worker.js 1000
> ^C
> $ node worker.js 1000
> ^C
> $ node worker.js 1000
> ^C
> $ node worker.js 1000
> ^C
> $ node worker.js 1000
> processing job: 1
> concluding job: 1
> 
> ^C
> $ node status.js
> {
>   waiting: 0,
>   active: 0,
>   succeeded: 1,
>   failed: 0,
>   delayed: 0,
>   newestJob: 1
> }
> $
> ```
> 
> ### Questions
> 
>     1. Why is the job not restarted immediately when the worker is instantiated after it has been terminated?

Hi @miguel-guedes 
Did you figure out the reason?
Even I am facing a similar issue.
If the worker is stopped before sending an acknowledgment. 
After the worker restarts, the job is not picked up. I have to restart the app multiple times so that it picks up the job.

**Comment by s888** [comment]
Hi @miguel-guedes
Did you figure out the reason?
Even I am facing a similar issue.
If the worker is stopped before sending an acknowledgment.
After the worker restarts, the job is not picked up. I have to restart the app multiple times so that it picks up the job.

**Comment by miguel-guedes** [comment]
@s888 I did not have much time available to put towards a fix for this issue and instead decided to use the `bull` package.

**Comment by hughsw** [comment]
- In your worker code, if no timeout is provided then the worker never resolves the promise, so the job never finishes (from Bee-Queue's perspective).  If you Ctrl-C quickly then the job will still be marked as in the active state.
- If you let the worker run long enough (stall interval), the job is marked as stalled.   The default stall interval is 5000 msec.  Then, after Ctrl-C and when you restart the worker, Bee-Queue notices that the jobs is stalled and restarts it.  But, with no timeout provided, it still won't resolve the promise or finish.
- If the job has stalled (you waited long enough before Ctrl-C), and you restart with a timeout, then the job will restart and run to completion.

The behavior appears non-deterministic because it depends on how quickly you Ctrl-C.

I don't believe there's a bug.
