### ISSUE TITLE
Reproducible: bee-queue loses track of jobs

### ISSUE THREAD

**Issue by hughsw** [bee-queue/bee-queue#189]
I have seen jobs that have successfully completed, but do not emit either of `succeeded` or `failed`.  The problem seems more likely on jobs that finish quickly.  It also may be influenced by the concurrency setting.

I would expect that any job that has had `job.save()` successfully resolve will eventually emit either `succeeded` or `failed`.  However, we can create and save jobs which never emit either of those job-level events.  We have observed this in Docker containers running under Docker for Mac and under Docker on Ubuntu on Digital Ocean droplets.  

Here's a repo that builds images that reliably demonstrate the problem, although not deterministically.

https://github.com/hughsw/stress-beequeue#run-the-bee-queue-client

This underlying issue may be the same as reported here #78

**Comment by hughsw** [comment]
I'm able to get this failure on a variety of cloud platforms (Docker for Mac, VirtualBox, Digital Ocean) and distributions (Ubuntu, Node, Alpine).  It reliably starts failing after things warm up with a few hundred quick jobs.

**Comment by hughsw** [comment]
I have a fix.  It's based on the analysis here #78 which is spot on.  However the 'crafty' ideas for solving the problem didn't pan out for me -- it's a race condition, and as such has to be faced head on rather than toyed with.

I have a fix.  It's successfully run over 128,000,000 jobs on my dev server overnight with no job failures and without dropping a single job.

It's simpler than I had thought, but it changes how job ids get created.  It keeps job-id-creation in the Queue rather than in Redis.

I am working to get the bee-queue test harness working in a Docker container environment.  I will see if I can add a test that exercises this bug, and that thus will prevent a regression.

I'll put up a WIP/RFC PR once I've teased out a bunch of debugging cruft from the code.

**Comment by hughsw** [comment]
I have not forgotten this issue -- I'm using the fix in our deployments.  But, I haven't had time to create the tests and make the minimal changes for the fix.

**Comment by bradvogel** [comment]
Mind putting a PR with the fix? Even a draft PR without tests would be helpful to us to understand the issue more.

**Comment by jdelman** [comment]
> I have not forgotten this issue -- I'm using the fix in our deployments. But, I haven't had time to create the tests and make the minimal changes for the fix.

Do you have a fork up?

**Comment by hughsw** [comment]
A PR with one approach to the problem is here #193

**Comment by hughsw** [comment]
I have spent a fair amount of time trying to make a bee-queue test that reproduces this problem.  So far, I have never seen the problem when the `queue.createJob()` and `queue.process()` code is running in the same Node process.  I believe a single Node process is the case in the `ava` testing harness.  Does anyone know of some kind of clustered Node testing harness that supports client/server tests using multiple Node processes?

My reproducible case has the `createJob()` queue in one Node process, and the `process()` queue in another Node process (as per our deployment architecture).  That is, the linux scheduler is in charge of asynchrony.  I am going to try to make a simpler reproducible case using docker-compose.

**Comment by hughsw** [comment]
I now have a relatively simple client/server  harness running via docker-compose.  I can reliably lose 2 to 3 percent of jobs in a configuration that has a throughput of 1500 to 2000 jobs / sec.

This exposes that there are memory-leak issues:
- lost jobs are added to the Queue.jobs set after they emit their 'succeeded' or 'failed' events, so the queue never removes these jobs from the Queue.jobs set
- one workaround to the lost jobs  problem (no 'succeeded' or 'failed' events on the job instance) is using the Queue's 'job succeeded' and 'job failed' events -- but, if you then use Queue.getJob() the job instance will be added to Queue.jobs and never deleted (again, because it got added after the events which would cause it to be removed from the set)
- it seems an oversight that Queue.removeJob() does not remove the job instance from the Queue.jobs set
