### ISSUE TITLE
How to throttle or rate limit?

### ISSUE THREAD

**Issue by gijo-varghese** [bee-queue/bee-queue#190]
I'm building a web scraper. Basically, the task of a worker is to download a page.

Each website needs to be downloaded at different rate limits. For example, website A must be downloaded at max 3 concurrent pages. website B at max 5 concurrent pages and website C at max 10 concurrent pages.

There might be 10+ workers and each website will have its own queue.

Is this possible with bee-queue?

**Comment by hughsw** [comment]
Yes.  bee-queue can handle the jobs and workers.  You need to write your own throttling or use an existing package.

Your job data would contain the website URLs or endpoints, and it would contain the details of the kinds of constraints you're talking about.

Your worker process would then use those constraints when it's pulling from the websites.  Don't  reinvent the throttling.  There are many solutions for various configurations, e.g. https://www.npmjs.com/package/limiter

**Comment by Eternal-Sunshine** [comment]
Bull library has built in rate limiter.
