### ISSUE TITLE
How to notify an user that the job is done and return the results

### ISSUE THREAD

**Issue by zefexdeveloper** [bee-queue/bee-queue#191]
I'm planning on creating a real time application where the user can send an image and this image will be processed and returned to the user when it's done, something really similar to what [convertio.co](convertio.co) does but I don't know how can I get access to the connected socket that requested the image manipulation in the job so I can notify when it's done. I want to notify the user using socket when the job was added to the queue, it's being processed and it's done (with the results).

**Comment by hughsw** [comment]
This doesn't sound like a bee-queue issue.  That is, bee-queue doesn't deal with your application's sockets or how your app works with the user.  

The bee-queue Job object is well-suited to notifying your app when the work is done, via the `succeeded` and `failed` events.
