### ISSUE TITLE
Can't use rediss TLS url - upgrade node-redis version

### ISSUE THREAD

**Issue by b-jam** [bee-queue/bee-queue#253]
To use redis with TLS - i.e. `rediss://` the node-redis version must be ideally greater than 3. 

The actual version implementing `rediss` was 2.8.X, so at a minimum that version which contains this commit.
https://github.com/NodeRedis/node-redis/commit/5d6e471d0c14df39974000427719c5d85fa4f21f

See https://github.com/NodeRedis/node-redis/issues/1331

**Comment by b-jam** [comment]
The current version in bee-queue is 2.7.x

**Comment by skeggse** [comment]
I'm gonna say we're not gonna address this before v2, which will use `ioredis`. Maybe if npm supported conditional dependencies or something but that'd be lunacy. The workaround described in #257 _should_ work but I haven't investigated.
