### ISSUE TITLE
Implementing a /status endpoint

### ISSUE THREAD

**Issue by cjroebuck** [bee-queue/bee-queue#256]
Hi there, I'm evaluating bee-queue for a feature I'm adding to my product. 

I'm wanting to create a long running job at one endpoint, the API will return instantly with a job id and allow clients to periodically poll a /status/:id endpoint which will get the current status of the job with the id until the job succeeds or fails.

I read in the docs that the Queue#getJob method shouldn't be used and to use job events, however in my use case I need to be able to retrieve a job when the user hits the /status endpoint, and this could be on any number of servers, not just the one that created the job - so can't rely on job events for this (i'm assuming). 

Am I understanding this correctly that my use case is not well supported by bee-queue or is there a better way that is supported? Thanks

**Comment by bradvogel** [comment]
Have you seen Arena? https://github.com/bee-queue/arena/. It shows the status of running jobs

**Comment by cjroebuck** [comment]
Thanks, so it seems the only way is to use queue.getJob even though the docs say it isn’t recommended.. hmm

https://github.com/bee-queue/arena/blob/744120be371291c8ca781930c3096117238f159f/src/server/views/dashboard/jobDetails.js#L13

**Comment by bradvogel** [comment]
It should be fine to use `getJob` on demand, such as the building a job status UI. This is Arena's use case too and why it uses `getJob` directly.

The hazard with `getJob` is that it runs a redis call each time to fetch the entire job. For most use cases where you just need a job id, you can get it from the event.
