### ISSUE TITLE
process(async (job)) should return promise?

### ISSUE THREAD

**Issue by ggb88** [bee-queue/bee-queue#269]
I may be misunderstanding the use of q.process() in the worker process and would like some clarification.  Here is the stub code I am using today.

```
etlQ.process(async (job) => {
    return new Promise(async function(resolve, reject) {
        try {          
            logger.info(`ETL handling job ${job.id} location ${job.data.location} as ${job.data.type}/${job.data.name}`);
            await ... do stuff;
            await etlQ.close();
            resolve(null);             
        } catch (x) {
            let str = `job ${job.id} exception: ${x.message}`;
            logger.error(str)
            await etlQ.close();
            reject(new Error(str));
        } 
    });
})
```

Is  .process() supposed to return a promise itself? chaining .then() returns an error?  The design I'm using requires the process to be "one-shot" and after the job has processed one and only one job in the q, there is some other processing to be done before exiting.  Thanks

**Comment by hughsw** [comment]
I'm guessing that closing the Queue from within the process callback is a problem.  Remove those statements to see if things work.  If you really really need to close the queue, do it from the Queue callback that happens after the job has completed...

Also, you have unnecessary layering of promise, async, and try/catch.  I would be doing something like this:
```
etlQ.process(async (job) => {
  logger.info(`ETL handling job ${job.id} location ${job.data.location} as ${job.data.type}/${job.data.name}`);
  doStuff(job).then(() => null).catch(err => {
    const str = `job ${job.id} exception: ${err.message}`;
    logger.error(str)
    throw new Error(str);
  });
});
```

**Comment by ggb88** [comment]
Thanks @hughsw.  co-incidently, I did refactor the code and it pretty much mirrors yours - except that I reverted to the callback style approach for .process, which allowed the process to operate as expected.  I've run some stress tests now with 5 processes reading the same Q and its run for 24hrs+ without issue.

```
etlQ.process( (job, done) => {
    doStuff(job.data.name, job.data.location).then(()=> {
        done();
        return etlQ.close( () => {
            process.exit(0);
        });
    }).catch( (x) => {
 ....
});
```
