### ISSUE TITLE
Scheduled jobs

### ISSUE THREAD

**Issue by vorillaz** [bee-queue/bee-queue#289]
Hey there, thanks for your awesome work.
I am looking for creating repeatable scheduled jobs.
Bull has a similar feature with a developer friendly API
```js
  // Repeat payment job once every day at 3:15 (am)
  queue.add(paymentsData, {repeat: {cron: '15 3 * * *'}});
```
Is it somehow possible to achieve a similar functionality with `bee-queue` ?

**Comment by skeggse** [comment]
The resolution to #81 still stands.
