### ISSUE TITLE
redis-sentinel support

### ISSUE THREAD

**Issue by velatrix** [bee-queue/bee-queue#295]
When I try to use the library with redis cluster it works fine but does not work with redis-sentinel. I saw some old issues about this which says it is not possible but those were from 2017. I wanted to ask if anything changed since then ?

**Comment by skeggse** [comment]
I'm not familiar with `redis-sentinel`, and we don't (yet) support it.

**Comment by hwp1984** [comment]
> When I try to use the library with redis cluster it works fine but does not work with redis-sentinel. I saw some old issues about this which says it is not possible but those were from 2017. I wanted to ask if anything changed since then ?

How to use the library with redis cluster? Could you please show me the code?
