### ISSUE TITLE
Documentation for checkHealth function

### ISSUE THREAD

**Issue by matteocontrini** [bee-queue/bee-queue#31]
In my use case of bq, I'm extracting about 2k documents from a database, and adding them one by one in the queue.
When all the 2k jobs have been processed, I need to start again (extracting the updated documents from the db and enqueueing them again).

The only issue is knowing when the queue is empty (which means all the jobs have been processed).
Bull has a `count` function on the queue, and bq seems to have a `checkHealth` undocumented function that's being used in tests only.

What do you think of naming that function something like `count` or `getCounts` and documenting it?
A parameter to specify which counts are needed would be nice as well.

**Comment by LewisJEllis** [comment]
Good catch; I didn't realize I hadn't documented it.

`getCounts` does sound like a better name. I'm not sure if it's worth the effort to specify which counts are needed - returning all of them is trivially more expensive than returning just one of them, and we can just let the consumer read whichever parts they need.

I've added this to my upcoming "todos".
