### ISSUE TITLE
Cannot avoid duplicate jobs

### ISSUE THREAD

**Issue by blazerguns** [bee-queue/bee-queue#360]
Hi,

I am not able to find a good way to avoid duplicate jobs. Lets say I create jobs with specific id, how would I make sure I dont create duplicate of same job given I have the id?

```
     chromeQueue.createJob(data);
        .timeout(8000)
        .retries(0)
        .setId('my_own_id')
        return njob.save()
    })
    .then((job) => {
        return res.status(200).send({"result": "success"});
    })
    .catch((err) => {
        return res.status(500).send({"result": "failed"});
    });
```
In the above I am setting my own id and assuming the I get another request with same id, I would like to verify if the job is already in queue. How can we achieve that? getJob seems to not work the way I thought it would. Not even sure if I should be using that for this purpose.

**Comment by bradvogel** [comment]
The `job.id` will be `null` if there's a job with that same id in the queue. See https://github.com/bee-queue/bee-queue#jobsetidid.

So something like this should work:
```
     chromeQueue.createJob(data);
        .timeout(8000)
        .retries(0)
        .setId('my_own_id')
        .save()
    .then((job) => {
        // The job.id will be null if the job is in the queue in ANY state (waiting, delayed, active, failed, succeeded, etc).
        const jobAlreadyInQueue = job.id === null;
        if (jobAlreadyInQueue) {
            return res.status(500).send({"result": "failed - job already in queue"});
        } else {
           return res.status(200).send({"result": "success"});
        }
    })
    .catch((err) => {
        return res.status(500).send({"result": "failed - other error"});
    });
```

Note that when a job is completed (either `succeeded` or `failed`), it'll remain in the queue and you can't ever re-use that job id to publish a new job. If you do not want this, consider passing `removeOnSuccess: true, removeOnFailure: true ` to the queue options.

**Comment by blazerguns** [comment]
Thanks for this. Helped clarify a lot. Is getJob() a safe way to check periodically to see contents of the job? Lets say, I submitted a job
"my_own_id" : {"do_this": "work"}
Assuming I set removeOnSuccess: true, removeOnFailure: true so as long as job is in queue with status like waiting, delayed would I be able to see the content {"do_this": "work"}. However I do not wish to dequeue.

**Comment by bradvogel** [comment]
Yup, you could use that to check status. If you're looking to build a status UI for the queue you should check out https://github.com/bee-queue/arena
