### ISSUE TITLE
Always get result as null on succeeded PUB/SUB

### ISSUE THREAD

**Issue by Rikhart** [bee-queue/bee-queue#382]
I have a producer and a consumer:

My producer is :
SERVER A:
In the producer a create a Job, then i listen a succeeded with a response wich has been processed in other server
```js
       const job = _bq_quaificationQueue.createJob({
            type: 'startup',
            classroomId:classroom.id
        });
        job.save();
        job.on('succeeded', function(result) {
          console.log(`Se vinculo el aplicativo ${job.id}`,result);
        });
```

My consumer server is B
SERVER B:  I handle some logic here, then use done(null, response[0]) to return a result for the SERVER A.
```js
_bq_quaificationQueue.process(async (job, done) => {
    var data = job.data;
    try {
      if (data.type == 'startup') {
        var Qualificationhub = server.models.qualificationhub;
        var response=await Qualificationhub.findOrCreate({
          where: {
            classroomId: ObjectID(data.classroomId)
          }
        }, {
          classroomId: ObjectID(data.classroomId)
        })
      }
      done(null,JSON.stringify(response[0]))
    } catch (error) {
      done(error)
    }
  })
```

The problem is that in SERVER A,  "succeeded" is called but result always get null.

```js
job.on('succeeded', function(result) {
          console.log(`Se vinculo el aplicativo ${job.id}`,result);
 });
```
I am using redis in the setup of my queues.

Please help me how to handle this situation, thanks.

**Comment by kmikodev** [comment]
I had the same problem and doing tests with a simple example I have realized that it is by using the async in the callback.

If at the time of executing the process I add the async then the value arrives as undefined
    
    queue.on('ready', () => {
      queue.process(async (job, done) => {
        console.log('processing job ' + job.id);
        await Promise.resolve()
        done(null, job.data.x + job.data.y);
      });
      console.log('processing jobs...');
    });
    
when I remove the async then if I receive the content in the 'succeeded' callback


    const logger = require('morgan');
    const express = require('express');
    const app = express();
    app.use(logger('dev'));
    
    const Queue = require('bee-queue');
    const queue = new Queue('express-example-2', {
      redis: {
        // port: 6379,
        // db: 0,
        password: 'XXXXX',
      },
    });
    queue.on('ready', () => {
      queue.process((job, done) => {
        console.log('processing job ' + job.id);
        Promise.resolve().then(s=>{
    
          done(null, job.data.x + job.data.y);
        });
      });
    
      console.log('processing jobs...');
    });
    
    app.get('/run/:x/:y', (req, res) => {
      const job = queue.createJob({
        x: req.params.x,
        y: req.params.y,
      });
    
      job.on('succeeded', (result) => {
        console.log('completed job ' + job.id);
        res.send('output: ' + result);
      });
    
      job.save((err) => {
        if (err) {
          console.log('job failed to save');
          return res.send('job failed to save');
        }
        console.log('saved job ' + job.id);
      });
    });
    
    const server = app.listen(4004, function () {
      const host = server.address().address;
      const port = server.address().port;
      console.log('Example app listening at http://%s:%s', host, port);
    });
