### ISSUE TITLE
Pass optional data in progress

### ISSUE THREAD

**Issue by mpinger** [bee-queue/bee-queue#39]
As a new feature, it would be helpful to be able to pass an optional object or message in the progress() call. The way it is done in kue would be fine.

Thanks,
mike

**Comment by LewisJEllis** [comment]
Sounds reasonable, I'll add this to the upcoming list.

**Comment by Rush** [comment]
I've got the same request.

**Comment by jeremyblalock** [comment]
It's relatively easy to remove the requirement for `progress` to be a number from 0–100. Then you could just pass an object with whatever values you want. Is there any downside to this approach? (I have tested it **[here](https://github.com/jeremyblalock/bee-queue)**, and it seems to work fine)

**Comment by stilliard** [comment]
I have a similar use case, but to pass data as different types of progress events: #107

**Comment by LewisJEllis** [comment]
@Rush @jeremyblalock I wrote some thoughts in #108 on some of my reservations toward this; if possible, I would like to get your feedback on your intended/imagined use cases for this so I can understand them and make sure we support them well. I especially want to make sure that those use cases are actually best served by progress events with arbitrary data (despite their caveats), rather than possibly by the usage of additional queues.

**Comment by jeremyblalock** [comment]
@LewisJEllis in my case I need that flexibility for two reasons:

1. To display both numerator & denominator in the progress (ex: **"Processing Page  5 / 11"**)
2. To display information about the current stage of the job.
    - In my case, users upload a multi-page file to a webserver, which then creates a processing job in bee-queue. The document is then processed page-by-page, and I want to show the title of the current page.

I was able to accomplish all this with my fork, by simply commenting out the code that does type checking on the progress value: https://github.com/jeremyblalock/bee-queue/commit/3fce87b3b71183ca8b8a752dceda272681daad44

**Comment by LewisJEllis** [comment]
Great, thanks for the rundown and specific examples! Those definitely sound like use cases where the context of "where was the event created" matters, the data is only available after starting the job processing, and we need to make sure the data makes it back specifically to whomever created the job. It's similar in spirit to the "progress bar for encoding a video upload" use case of the numeric progress.
