### ISSUE TITLE
Update Node Redis to latest

### ISSUE THREAD

**Issue by NoNameProvided** [bee-queue/bee-queue#396]
The latest release of Node Redis contains support for the `wss` connection string format what we would like to use. Is it possible to bump the `redis` dependency to latest and make a release? I have not tested bee-queue locally, but from looking at the changelog at Node Redis I don't see any change what would break bee-queue.

**Comment by KimBurrows** [comment]
+1 for this.  Could you please update to at least Redis 3.1.1, due to the security vulnerability in older versions?

**Comment by skeggse** [comment]
We're blocked on bee-queue v2, because upgrading to Redis 3 is a breaking change. General support for this project has mostly stalled.

**Comment by NoNameProvided** [comment]
I don't follow, why updating an underlying package is considered a breaking change? Only the node-redis connection options is exposed through this lib and I don't see any breaking changes there.

**Comment by NoNameProvided** [comment]
I see, thanks for the detailed explanation! I will go ahead and close this issue, because if I understand correctly, the driver update will be in the next major version, whenever it gets released.
