### ISSUE TITLE
Recreate queue on initial redis connection failure

### ISSUE THREAD

**Issue by jannikkeye** [bee-queue/bee-queue#409]
How can I properly recreate a queue if the initial connection to redis fails? There are no attempts to create a new connection. I'm trying to do that from the error event handler but to no avail. I need behavior that retries establishing the initial connection. Connection loss after the initial connection has been established is fine and is reconnecting is working fine.

**Comment by dheimoz** [comment]
Hello @jannikkeye , do you mind sharing your solution? The best way to improve Open Source Software is by sharing.
Thanks.

**Comment by jannikkeye** [comment]
Essentiell I catch the unhandledRejection that is thrown when bee queue cannot establish the redis connection and then attempt to initialize a new queue.

```typescript
export const initQueue = () => {
  queue = new Queue("queries", queueOptions);

  queue.process(10, async (job: any, done: BeeQueue.DoneCallback<any>) => {
    await handleJob(job);

    return done(null);
  });

  queue.on("error", async (err) => {
    if ((err as any).errno === -61) {
      await queue.close();

      initQueue(setHealthStatus);
    }
  });

  queue.on("failed", (job, err) => {
    logger.error(`beequeue::job::failure::${job.id}`);
    logger.error(err.message);
  });

  return queue;
};
```

```javascript
process.on("unhandledRejection", async (e) => {
    if (e.errno === -61) {
      await wait(3000);

      initQueue();
    }
  });
```

This approach doesn't work well with the built in reconnect behavior after an initial connection is lost though. So currently the queue is always recreated on any connection failures.

Not sure if that's the best solution. I'm sure there's a better one but that currently works for me.
