### ISSUE TITLE
Job logging for Arena

### ISSUE THREAD

**Issue by PseudoCoding** [bee-queue/bee-queue#417]
bee-queue/arena supports view logs from jobs. Is there any functionality on the queue side that supports this? Most of the logging documented in the readme for bee-queue seems to point to basic console logging.

**Comment by bradvogel** [comment]
Arena supports more than just Bee Queue. It supports Bull and BullMQ also. The 'logs' feature is only available for Bull and BullMQ and uses their `getJobLogs()` API. Bee queue doesn't have a similar API.

**Comment by PseudoCoding** [comment]
So I'm guessing there is no plan for BeeQueue to expose an API to provide this functionality?
