### ISSUE TITLE
Prevent retry on fatal/critical error

### ISSUE THREAD

**Issue by mpinger** [bee-queue/bee-queue#42]
I would like a way to circumvent 'retrying' jobs and go directly to the 'failed' event if I know that a retry will never succeed. This is useful if the the data passed into a job was invalid, for example.

Perhaps there could be a job method that can be called to fail the job from inside the job handler or prevent retries from happening?

**Comment by LewisJEllis** [comment]
I'm not sure what the difference is between what you're describing and having the handler do something like:
```javascript
return done(new Error('Job cannot complete, invalid input'));
```

**Comment by mpinger** [comment]
Queue = require('bee-queue');
    var test = new Queue('test');
    var job = test.createJob({})
        .retries(5)
        .on('retrying', function(err) {
            console.log('retrying ' + err);
        })
        .on('failed', function(err) {
            console.log('failed ' + err);
        })
        .save();

    test.process(function(job, done) {
         if (!job.data.foo) {
             return done(new Error('Job cannot complete, invalid input'));
         }
         done(null, job.data.foo);
    });

The above prints:

    retrying Error: Job cannot complete, invalid input
    retrying Error: Job cannot complete, invalid input
    retrying Error: Job cannot complete, invalid input
    retrying Error: Job cannot complete, invalid input
    retrying Error: Job cannot complete, invalid input
    failed Error: Job cannot complete, invalid input

I would like a way to make it do just this:

    failed Error: Job cannot complete, invalid input

I don't want to just turn off retries because if the initial validation passes there are other failures (not shown above) on which I would want to retry.

**Comment by tamlyn** [comment]
What about calling `job.retries(0)` before failing it? I haven't tested it but I think that should prevent the job from being retried.

**Comment by skeggse** [comment]
@tamlyn is correct.

It might make sense to add a `Job#fail` method to force the retries to `0`.

**Comment by skeggse** [comment]
I'm adding a test for this in 256ced1/`1.1.0`. I'm not super fond of `Job#fail` after further consideration - it makes it sound like it'll fail the job immediately (and perhaps even accept an `Error`), whereas the preferred mechanism for failing the job is still rejecting the promise or throwing/calling back with an error.

If you have thoughts about a nicer API for this, please reopen!
