### ISSUE TITLE
crashes after 3 jobs

### ISSUE THREAD

**Issue by ryantupo** [bee-queue/bee-queue#421]
using beeque to scrape websites and que them up when i use the code ive written to only print out each job ID it works fine but when i add the scraping function call it works for 3 then starts the 4th and crashes the terminal wont even let me ctrl - c to stop it wont work.

Processing job google.com
DONE - 2021-07-07 11:37:8
DONE - 2021-07-07 11:37:8
Processing job youtube.com
3
DONE - 2021-07-07 11:37:11
DONE - 2021-07-07 11:37:11
Processing job tmall.com
DONE - 2021-07-07 11:37:14
DONE - 2021-07-07 11:37:14
Processing job baidu.com

the done printouts show when its finished the job and even with a try catch getting no errors any help would be much appreciated.

**Comment by bradvogel** [comment]
Do you have code you could share?
