### ISSUE TITLE
What if the jobId is reached its maximum?

### ISSUE THREAD

**Issue by yarosdev** [bee-queue/bee-queue#422]
Why not check jobId before adding to reset it to 1 when it reaches 32bit int max?

**Comment by bradvogel** [comment]
I believe it's a 64-bit integer: https://github.com/bee-queue/bee-queue/blob/master/lib/lua/addJob.lua#L11 and https://redis.io/commands/INCR. Bee queue currently doesn't handle an overflow. Is there a risk you'll hit that?

**Comment by bradvogel** [comment]
Yup, but nearly impossible to overflow. Even if your queue was processing 1 job a millisecond, it'd still take 292 million years to hit the 64-bit max.
