### ISSUE TITLE
Best practice for API routes

### ISSUE THREAD

**Issue by sridharraman** [bee-queue/bee-queue#426]
I am building an API gateway with multiple routes. Some of the database operations for these routes are long and complex and hence, I would like to use the job-queue approach. I am using bee-queue for this. Are there any best practices for this scenario?

Before adding the job-queue, each API route had a helper function that would take care of the db querying. But now, if I create a job for the queue, how do I take care of the implementation of the helper function? Is it possible to send a function as a parameter to a job?

Or do I create separate queues for each API route so that the functionality of the .process remains consistent within the queue?

**Comment by bradvogel** [comment]
Parameters that you pass to a job must be serializable into json since they’re stored in Redis. So you’ll need to pass all the information needed for the database query when you create the job.
