### ISSUE TITLE
Job progress only updates via messages

### ISSUE THREAD

**Issue by patriceperez** [bee-queue/bee-queue#43]
While trying to get the job progress via the `Queue.getJob()` API, the progress is always 0

Here is the reproduction: https://tonicdev.com/56dc46f40ba4470d0091e3c2/56dc46f40ba4470d0091e3c3

(please note that the redis instance connection is through a free service for the reproduction to work, so if you get a connection error just retry to run the provided code)

perhaps I'm doing something wrong?

**Comment by patriceperez** [comment]
@LewisJEldid did you get a chance to look at this?

**Comment by Americas** [comment]
I might be mistaken, but it seems to be sync/async problems. Due to the for loop.

https://tonicdev.com/570cd3203b688414008b3d6f/bee

**Comment by patriceperez** [comment]
@Americas 
how do you mean?

**Comment by Americas** [comment]
a for loop is synchronous, so when it calls other functions, they will be added to a function queue, and only run when the current function stops.

But to check job progress you can just use the `job.on("progress", function(){} )` and it works by events.

**Comment by patriceperez** [comment]
yeah, that is established - however on redis the key for the job details
does not update with the progress nor the status at the moment.

I know the status issue has been resolved but was not released yet though...


Patrice Perez
Monitoring  | Kenshoo
*Office* +972 73 2862 415
*Mobile* +972 50 7160 506
www.Kenshoo.com <http://www.kenshoo.com/>
[image: Transform your marketing. Grow your business.]
<http://www.kenshoo.com/>

On Tue, Apr 12, 2016 at 4:30 PM, Ricardo Lopes <notifications@github.com>
wrote:

> a for loop is synchronous, so when it calls other functions, they will be
> added to a function queue, and only run when the current function stops.
>
> But to check job progress you can just use the job.on("progress",
> function(){} ) and it works by events.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/LewisJEllis/bee-queue/issues/43#issuecomment-208905455>
>

-- 
This e-mail, as well as any attached document, may contain material which 
is confidential and privileged and may include trademark, copyright and 
other intellectual property rights that are proprietary to Kenshoo Ltd, 
 its subsidiaries or affiliates ("Kenshoo"). This e-mail and its 
attachments may be read, copied and used only by the addressee for the 
purpose(s) for which it was disclosed herein. If you have received it in 
error, please destroy the message and any attachment, and contact us 
immediately. If you are not the intended recipient, be aware that any 
review, reliance, disclosure, copying, distribution or use of the contents 
of this message without Kenshoo's express permission is strictly prohibited.

**Comment by Americas** [comment]
Well, it worked on my tweaked version of your code

**Comment by patriceperez** [comment]
all your iterations still output 0 as the progress, am I missing something?

**Comment by Americas** [comment]
when I run it, although it has a delay, the progress is updated.

The first tick shows 0, the second 25, and the last has 75.

**Comment by patriceperez** [comment]
I'm not seeing it - when I run your code it outputs progress as 0 until the job is done, which gets progress up to 100 instantly

**Comment by skeggse** [comment]
I'll add a unit test for this functionality in #64.

**Comment by skeggse** [comment]
This is indeed the current behavior. Feel free to submit a PR to change this behavior. Also open to documentation PRs if you think this behavior is unclear from the README.

**Comment by primadi** [comment]
I have long job process, so my scenario is :
1. call queue.createJob and return jobId to client
2. using timer, from client, call queue.getJob to ask progress, but like this issues, progress always 0.

Perhaps I am doing wrong ? what is right scenario for my problem ?

**Comment by primadi** [comment]
looking to source code, reportProgress communicate using event, not updating job progress..

Am I have to track progress manually, or there is another way ?
