### ISSUE TITLE
Unable to retrieve result of job

### ISSUE THREAD

**Issue by sridharraman** [bee-queue/bee-queue#430]
I am sharing a gist here that explains my problem - https://gist.github.com/sridharraman/a4bb913e610bf8ca738031d216a45e2f

On making an API request, I create a job and return the job.id. I then have another route to access the status of the job. Unfortunately, I am only able to get the job's status, progress, but not the result that would have been returned by the process handler. Any idea why?

**Comment by bradvogel** [comment]
Thanks for the full example. Unfortunately the job result isn't stored with the job. It's only emitted in the 'success' event.

As a hacky workaround, you could store the object in the `progress` property, which is stored in redis. So modify your job processor like this:

```
apiQueue.process(3, (job, done) => {
  console.log("processing ...");

  job.reportProgress({ parA: "hello", parB: "world!" });

  done();
});
```
