### ISSUE TITLE
Job added event?

### ISSUE THREAD

**Issue by alexdonh** [bee-queue/bee-queue#431]
Maybe I am the only one asking for it? A `job added` local event (for queue) fired right after a job is added?

**Comment by scalalang2** [comment]
I think the callback function of the Promise of `save` function could help you.
You can implement your own event listener.

```javascript
const job = addQueue.createJob({x: 2, y: 3});
job
  .timeout(3000)
  .retries(2)
  .save()
  .then((job) => {
    // job enqueued, job.id populated
  });
```
