### ISSUE TITLE
Is it possible to set always retry when creating job

### ISSUE THREAD

**Issue by kth-tw** [bee-queue/bee-queue#434]
I want to always retry a job, but `.retries()` need a number for retrying times.  
It work when I write `job.retries(1)` in process. 
example:
``` typescript
import Queue from 'bee-queue'
const queue = new Queue('test', {
  activateDelayedJobs: true,
})

queue.process(async (job) => {
  doSomething()
  if (someError) {
    job.retries(1)
    throw new Error()
  }
}
But I hope to specify a job always retry when creating.

**Comment by bradvogel** [comment]
Currently Bee Queue doesn't support infinite retries. The code you have should work for resetting the number of retries each time you process. You could also perhaps pass something like `Number.MAX_SAFE_INTEGER` when creating the job.

**Comment by kth-tw** [comment]
If I need this feature, where can I suggest a new feature? Or create a new pull request directly?

**Comment by bradvogel** [comment]
Yeah, please file a new issue requesting this feature. We can then discuss the use cases and see if it'd be a useful improvement to the library.
