### ISSUE TITLE
feature: create a infinite-retrying job

### ISSUE THREAD

**Issue by kth-tw** [bee-queue/bee-queue#435]
According to #434 , there is no way to create a job which always retry after error.  
The solution suggest by @bradvogel is use `Number.MAX_SAFE_INTEGER`. 
```
const job = addQueue.createJob({x: 2, y: 3});
job
  .retries(Number.MAX_SAFE_INTEGER)
  .save()
  .then((job) => {});
```
Should add a new function of job which mark the job always?  
For example: 
```
const job = addQueue.createJob({x: 2, y: 3});
job
  .alwaysRetry()
  .save()
  .then((job) => {});
```
when call `.alwaysRetry()`, add an option to job.
If the option exist, do retry without determining if `job.options.retries > 0`

**Comment by bradvogel** [comment]
Can you share more about your use case for a job that retries an infinite number of times? Is it some recurring task?

**Comment by kth-tw** [comment]
My case is trying to call api to ask server if a job is success, and do something after the job is success

**Comment by bradvogel** [comment]
Ok, and what's the "something" you do after the job is a success? Could that publish a new one-time job?

**Comment by kth-tw** [comment]
So you prefer creating a new job rather then retry the same job?
It would causes the number of job increase.
In my opinion, the new job do same thing (trying to call api ), it should be the same job.

**Comment by bradvogel** [comment]
Yes, I would always create a new job for each task, eg calling an API once. By having a separate job per call, you'll know exactly what time the job was created and be able to retry failures a certain number of times.
