### ISSUE TITLE
Jobs occasionally stuck in "waiting"

### ISSUE THREAD

**Issue by dhruska** [bee-queue/bee-queue#438]
We're debugging an issue and wondering if there is anything obvious we're overlooking. Our setup includes multiple webserver instances and multiple worker instances, and a scheduler instance with roughly a dozen different Bee queues. Our queues are created with a `stallInterval` of 5000, and the non-worker queue instances call `checkStalledJobs` every 5000 ms.

We are occasionally running into a situation where our queues fill up with jobs stuck in the "Active" state, and then the "Waiting" state. It looks like perhaps our worker instances are trying to process the jobs, but are having trouble connecting to our database (or some other issue) that is causing the processing of the jobs to hang. I would think, because we are calling `checkStalledJobs`, these jobs would be terminated and re-enqueued after a maximum of 5000 ms. However, this doesn't seem to be happening. Is there something obvious I'm overlooking here?

Something else to note: this happens for ALL of our different queues at the same time, and only resolves after restarting every instance a few times.

**Comment by skeggse** [comment]
A job stalls when its worker stops reporting in to Redis (e.g. the process crashes); you probably want to set a job timeout for this failure mode.
