### ISSUE TITLE
What happens if you delete all bq redis keys

### ISSUE THREAD

**Issue by vezzick** [bee-queue/bee-queue#443]
If I delete all the bq redis keys, will it have any detrimental effects? Note that I don't care if in progress jobs succeed or don't succeed, I simply want future operations on the servers to work and for all past jobs to be deleted from redis.
I think this is safe as it should effectively be like creating a new beequeue setup with a new redis, but please correct me if I am wrong.
This is the simplest way for me to clear the large amount of memory bq is now using in redis.

**Comment by bradvogel** [comment]
Bee Queue will create all the necessary Redis keys upon startup. Before clearing Redis, ensure Bee Queue is not running. If you clear it while Bee Queue is running, it will likely lead to data corruption. Once you clear Redis and start Bee Queue up, you should be fine.

**Comment by vezzick** [comment]
Thanks!
