### ISSUE TITLE
How to check if bee-queue is empty or not?

### ISSUE THREAD

**Issue by scalalang2** [bee-queue/bee-queue#447]
Hi,
I implemented the simple job worker.

It works through following steps:
1. **if the queue is empty,** process apply about 1,000 jobs on the queue.
2. Then, the workers recieve jobs from queue. Usually it takes about 2-3 minutes.

In first step. I implement it as follow.
```javascript
return (await init_queue.getJobs('waiting', {start:0, end:10})).length == 0 &&
        (await list_queue.getJobs('waiting', {start:0, end:10})).length == 0 &&
        (await content_queue.getJobs('waiting', {start:0, end:10})).length == 0 && 
        (await persist_queue.getJobs('waiting', {start:0, end:10})).length == 0 &&
        (await list_queue.getJobs('active', {start:0, end:10})).length == 0 &&
        (await content_queue.getJobs('active', {start:0, end:10})).length == 0 && 
        (await persist_queue.getJobs('active', {start:0, end:10})).length == 0
```

But I think. It doesn't work as I expected.
What's the proper way to check queue is empty or not?

**Comment by bradvogel** [comment]
Can you share more about the reason you need to wait for the queue to be empty? Is it that you want to ensure that not too many jobs are processed at once? If so, take a look at the concurrency setting for jobs. Or is it that you need a hook that jobs are complete? Take look at the `succeeded` event.

**Comment by scalalang2** [comment]
It doesn't mean that I need to implmenet the listener executed when queue is empty.
I just want to check the queue is empty or not.

**Comment by scalalang2** [comment]
I implemented this like below.
I think this issue is resolved.

```javascript
async function isQueueEmpty(): Promise<boolean> {
    let init_health = await init_queue.checkHealth()
    let list_health = await list_queue.checkHealth()
    let persist_health = await persist_queue.checkHealth()
    let content_health = await content_queue.checkHealth()

    return init_health.waiting == 0 &&
        list_health.waiting == 0 &&
        persist_health.waiting == 0 &&
        content_health.waiting == 0
}
```
