### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by patriceperez** [bee-queue/bee-queue#45]
it's been pretty dead here for a while now

**Comment by v4l3r10** [comment]
bee-queue seems to work very fine... so we not need update for now :)

**Comment by matteocontrini** [comment]
@v4l3r10 actually no ;) there are many open issues with improvements that @LewisJEllis has said he would have completed at some time

**Comment by patriceperez** [comment]
@matteocontrini is correct, however I was referring to the communication on issues as well

**Comment by shinzui** [comment]
I would also like to know the status of the project. Also, is there a list of companies that are using bee-queue in production?

**Comment by matteocontrini** [comment]
@LewisJEllis up

**Comment by thelinuxlich** [comment]
You guys should try NSQ. Much better for this kind of job.

**Comment by patriceperez** [comment]
thank you for the suggestion, however NSQ is a messaging queue - not a job queue (it can be converted into one, though it does require some effort)

Additionally it's not based in Node.js...

I appreciate you trying to help :+1:

**Comment by matteocontrini** [comment]
Does anyone know other projects that are similar to bee-queue and that "just work"? Even if they're not based on Redis.

**Comment by thelinuxlich** [comment]
It depends how much persistence you want...NSQ will save failed jobs on RAM and after than on disk to resend again(and it has exponential backoff builtin). And it is brokerless.

**Comment by grantcarthew** [comment]
I didn't like the state of Queues and decided to write my own:
https://github.com/grantcarthew/node-rethinkdb-job-queue

It has been a few months work, however after greater than 700 integration tests, I am starting to think I am getting close to publishing it.

It is using RethinkDB in the backend.

Sorry, doesn't really meet the "just work" criteria yet. I estimate I will be finished with the code for publishing to NPM in a week or two. All I have left to work on is the change feed event notification, and tests for the main Queue object. That's not much. Then I will be writing documentation.

If you are not using RethinkDB, maybe another queue would be a good options. The ones I looked at are [Kue](https://github.com/Automattic/kue) and [Bull](https://github.com/OptimalBits/bull).

**Comment by skeggse** [comment]
Hey folks, we just released the `1.0.0` of bee-queue.
