### ISSUE TITLE
Python implementation for bee queue

### ISSUE THREAD

**Issue by p9f** [bee-queue/bee-queue#450]
Hi,

First of all, thank you for your job on this awesome library.

I need a message queue similar to bee-queue, but including:
- a python implementation
- a way to consume messages by batch

Use case is about analytics data being produced by a node.js backend and a django backend, and consumed by some python workers.

I wonder:
- do you know about any python implementation of bee queue, compatible with the node.js client?
- if not, and if I write the python client, would you consider linking to this python client in your repository?

Best regards,

**Comment by bradvogel** [comment]
> First of all, thank you for your job on this awesome library.
Thanks! The team appreciates your compliment.

> do you know about any python implementation of bee queue, compatible with the node.js client?
I don't know of any.

> if not, and if I write the python client, would you consider linking to this python client in your repository?
Absolutely!
