### ISSUE TITLE
Update job's delayUntil?

### ISSUE THREAD

**Issue by blueberry6401** [bee-queue/bee-queue#455]
Hi, this is a question.
Inside my `process` method, in some cases, I decide to give the job one more try but with the delay, like this:
`job.delayUntil(Date.now() + DELAY_RETRY).retries(1)`
Job did retried, but the delayUntil does not have any effect. The job is retried immediately after throw.
Can you help? Thanks.

**Comment by bradvogel** [comment]
Try calling `save()` at the end, eg `job.delayUntil(Date.now() + DELAY_RETRY).retries(1).save()`
