### ISSUE TITLE
job scheduler

### ISSUE THREAD

**Issue by icfr** [bee-queue/bee-queue#46]
did you think this will be a good method to add scheduling job ?

http://blog.codezuki.com/blog/2013/07/07/redis-queue

**Comment by skeggse** [comment]
We're adding delayed jobs in #64, although it may not (yet) be as scalable as the approach in the linked post. That said, relying on redis pubsub to handle keyspace expirations won't work well for a queue that may be embedded in a Redis instance handling other data or tasks.
