### ISSUE TITLE
Update dependency

### ISSUE THREAD

**Issue by OSN64** [bee-queue/bee-queue#47]
The redis dependency is at 1.0.0 whilst the latest release is at 2.5.3.
An update would add performance. Are there any issues with upgrading?
I have ran the tests under version 2.5.3 and they all pass.

**Comment by sorin** [comment]
I actually upgraded our fork to the latest node-release, changes are minimal and it seems to be working fine in production, i'd be happy to send a PR if there's anybody around to merge it

**Comment by kerberjg** [comment]
Same here, we're having trouble with the different APIs as one part of our code uses the latest version of Redis, while Beequeue's is outdated

**Comment by skeggse** [comment]
Resolving this in #64.

**Comment by skeggse** [comment]
Up-to-date as of `1.0.0`.
