### ISSUE TITLE
Redis/keydb v6 usage of "AUTH <username> <password>"

### ISSUE THREAD

**Issue by OneBitAhead** [bee-queue/bee-queue#472]
Hi, we are using KeyDB with the new AUTH feature that enables us to connect to keydb/redis with a username-password-pair. This allows us to use ACLs within the Keydb namespace. 

My Question: Do you plan to upgrade to a newer redis-client version (i think >3.9 is needed) in the near future or at all? 

Currently there is no way to use this feature (if i am not mistaken?) 

Thanks in advance
By the way: Nice fast queue implementation :)

**Comment by compwright** [comment]
@OneBitAhead We have updated to redis 3.1 (works with any 3.x), and will be updating to redis 4 soon. Let us know how it goes!
