### ISSUE TITLE
Unique job pattern

### ISSUE THREAD

**Issue by jorenvandeweyer** [bee-queue/bee-queue#483]
I've been using Bee-Queue for a while now, but there is still one question that I can't solve.

When I want to prevent a job from being added twice to the queue, I give them a JobID that I can recreate when my code is creating new jobs. This works perfectly.

When a job ran successfully, the last step of the job is deciding if and when it should run again (the new job will have the same JobID). This information is written to a table in my database (some other code periodically checks this table if it should create new jobs). After this step my job is marked as "done" (this will make sure the job will be ran again in the future if needed).

Now I wanted to implement the same behaviour using scheduled jobs (for performance reasons). But when I tried to schedule a job before marking the job as done, it'll say the job already exists. 

Can someone help me in the right direction how this can be implemented?

**Comment by compwright** [comment]
@jorenvandeweyer are you trying to do a recurring job?

**Comment by jorenvandeweyer** [comment]
Kinda, I want to be able to reschedule a succesfull job, with a variable delay (which is computed during the job)
