### ISSUE TITLE
ioredis is not being detected by bee-queue

### ISSUE THREAD

**Issue by sebaplaza** [bee-queue/bee-queue#484]
Hello,

`ioredis` constructor is not being detected as a valid client in `bee-queue`, and its using the fallback internal redis client instead.

example:

```js
import Redis from "ioredis";

(async () => {
  const redis = new Redis();
  console.log(redis.constructor.name);
  await redis.disconnect();
})();

==> output : EventEmitter
```

`bee-queue` is using the next function to check the redis client.

https://github.com/bee-queue/bee-queue/blob/master/lib/redis.js#L67

as you can see, we cannot use `EventEmitter` as a solution to detect `ioredis`.

Maybe we can use the presence `.status` as a standard method ?

**Comment by jcurbelo** [comment]
I'm having the same issue, not being able to use `ioredis` as a Redis client. Is there any workaround to this?

**Comment by jcurbelo** [comment]
Got a workaround for this issue, since bee-quee relies on `constructor.name` to check if `"redis"` is a Redis client, I created a new class `RedisClient` that inherits from `Redis`. The new inherited member will have `constructor.name = RedisClient`.

```typescript
import Redis from 'ioredis';

class RedisClient extends Redis {
  constructor(redisUrl: string) {
   // change your ctor according to your settings
    super(redisUrl);
  }
}

 const redis = new RedisClient('your-redis-url');
 console.log(redis.constructor.name); // prints RedisClient
 
 const config = {
  redis: redis,
};

const queue = new BeeQueue('your-queue', config);

```

**Comment by compwright** [comment]
ioredis is not supported, and there are currently no plans to add support.

**Comment by sebaplaza** [comment]
Really? why ?

Are you accepting PRs for support this ?

**Comment by compwright** [comment]
Mainly because there are bigger fish to fry (take a look at the outstanding issues), and secondarily because an adequate workaround has been provided above if it is important to you to use Bee-Queue with ioredis.
