### ISSUE TITLE
Benchmarks are outdated

### ISSUE THREAD

**Issue by manast** [bee-queue/bee-queue#50]
The latest version of bull (https://github.com/OptimalBits/bull) is much faster now, probably up to 95% the speed of bee-queue, so the benchmark page should reflect this fact not to give a wrong picture of the comparison between the different queues available for node.

**Comment by akrawchyk** [comment]
@manast just curious, do you have recent benchmarks for bull?

**Comment by v4l3r10** [comment]
i have done some tests on my machine with new version of kue and bull.
these are my results:

Bull 1.0.0
Ran 10000 jobs through Bull with concurrency 1 in 7748 ms
Ran 10000 jobs through Bull with concurrency 5 in 4419 ms
Ran 10000 jobs through Bull with concurrency 20 in 3523 ms
Ran 10000 jobs through Bull with concurrency 50 in 3325 ms


Kue 0.11.1
Ran 10000 jobs through Kue with concurrency 1 in 14644 ms
Ran 10000 jobs through Kue with concurrency 5 in 11004 ms
Ran 10000 jobs through Kue with concurrency 20 in 10960 ms
Ran 10000 jobs through Kue with concurrency 50 in 10789 ms

BeeQueue
Ran 10000 jobs through Bee-Queue with concurrency 1 in 4769 ms
Ran 10000 jobs through Bee-Queue with concurrency 5 in 3375 ms
Ran 10000 jobs through Bee-Queue with concurrency 20 in 3399 ms
Ran 10000 jobs through Bee-Queue with concurrency 50 in 3474 ms

**Comment by skeggse** [comment]
Benchmarks updated; I'm not seeing the same performance parity. We do still need to add more comprehensive Redis benchmarks that show how its resource utilization compares. Filed as #67.
