### ISSUE TITLE
Is it possible to create something like this in Bee queue?

### ISSUE THREAD

**Issue by Tuner32** [bee-queue/bee-queue#506]
I want to create a user queue for each group. When a user sends an item to another user, there are several tasks. If you make it multi-threaded, you will get an error when executing concurrently in the middle.

So I'm trying to apply a grouping queue, but it's far from what I'm going to use, because, this is an extreme example. -> Transfer process to B is running, C-> Transfer process to B is running, but if there are multiple workers, it is assumed that the data is updated in a state that has already received a value and is mixed with past data. I'd like to eventually create a group when sending from A->B, and make it wait and act on if the group exists when sending from C->B. If someone else sends to C, they add it to the A->B queue, not the other worker. If that's the case, I think it'll work well in the end. This is my first experience with this kind of production, so I may be inexperienced. I'm sorry. If there is another way, please limit it.

**Comment by compwright** [comment]
@Tuner32 I've opened up the discussion section, please feel free to re-post over there.
