### ISSUE TITLE
Error in production: Lua script cache

### ISSUE THREAD

**Issue by kalvish21** [bee-queue/bee-queue#51]
I keep getting this error in production:

```
error: A queue error happened: Could not build Lua script cache
```

I'm using an ubuntu machine on EC2. What is the possible remedy for this?

**Comment by vodanh1213** [comment]
just update your redis to latest, old version caused it.

**Comment by skeggse** [comment]
If you're still experiencing this issue, and continue to experience it after #64 merges, feel free to re-open.
