### ISSUE TITLE
Using bee-queue to build saved search + email alerts

### ISSUE THREAD

**Issue by younes-alouani** [bee-queue/bee-queue#514]
Dear community,

This is not a problem. I had to post it here because I couldn't find a discussion section. 

I am developing an app to list cars for sale.

I would like to add a "saved search" feature similar to Ebay or Linkedin.

A user can search for a car using the following attributes:

- Year
- Keyword
- Model
- City

The user can then save this search and receive daily emails of new ads posted that match their search.

Do you have any comments on how to implement this feature?

**Comment by compwright** [comment]
@younes-alouani I've opened discussions, feel free to re-post over there.
