### ISSUE TITLE
Question: Why BQ moves stalled jobs in front of the queue?

### ISSUE THREAD

**Issue by aletorrado** [bee-queue/bee-queue#52]
Hi,

I've been having a bug in which I got a very small amount of jobs that always stalled. I've noticed that BQ always moves them in front of the queue, making the entire queue to stall.

Of course, it would not happen if the stalling reason would be some network error or any other self-repairing issue.

What do you think about moving them to the last position?

**Comment by skeggse** [comment]
We're addressing this in #64.

**Comment by skeggse** [comment]
Stalled jobs go to the end of the queue as of `1.0.0`.
