### ISSUE TITLE
Running on redis cluster

### ISSUE THREAD

**Issue by ltkrbk** [bee-queue/bee-queue#563]
I try to a redis cluster with below settings:
`
const JobMain 		= new Queue('queue', {
	prefix: 'bq',
	redis: redis.createCluster({
		rootNodes: [
			{
				url: "redis://server1.s1.com:7001",
			},
			{
				url: "redis://server2.s1.com:7001",
			},
			{
				url: "redis://server3.s1.com:7001",
			},
			{
				url: "redis://server4.s1.com:7001",
			},
		],
		useReplicas: true,
		defaults: {
			password: "123456"
		},
	}),
});
`
How ever it gives me error:
`
A queue error happened: Ready check failed: NOAUTH Authentication required.
/home/queueJob/node_modules/redis-parser/lib/parser.js:179
    return new ReplyError(string)
           ^

ReplyError: Ready check failed: NOAUTH Authentication required.
    at parseError (/home/queueJob/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/queueJob/node_modules/redis-parser/lib/parser.js:302:14) {
  command: 'INFO',
  code: 'NOAUTH'
}
`
I try connect directly with redis with blow code and works totally fine:

`
const redis 		= require('redis');
const cluster = redis.createCluster({
	rootNodes: [
			{
				url: "redis://server1.s1.com:7001",
			},
			{
				url: "redis://server2.s1.com:7001",
			},
			{
				url: "redis://server3.s1.com:7001",
			},
			{
				url: "redis://server4.s1.com:7001",
			},
	],
	useReplicas: true,
	defaults: {
		password: "123456"
	},
});

(async () => {
	
cluster.on('error', (err) => console.log('Redis Client Error', err));

await cluster.connect();

await cluster.set('hello', 'cluster');
const value = await cluster.get('hello');
console.log(value);

cluster.disconnect();
})();
`

Output:
`
cluster
`

Any suggestions?

**Comment by henriqueguedes-developer** [comment]
You can try adding the password directly to the Redis connection URL, as in the example below:
const JobMain = new Queue('queue', {
  prefix: 'bq',
  redis: redis.createCluster({
    rootNodes: [
      { url: "redis://username:password@server1.s1.com:7001" },
      { url: "redis://username:password@server2.s1.com:7001" },
      { url: "redis://username:password@server3.s1.com:7001" },
      { url: "redis://username:password@server4.s1.com:7001" }
    ],
    useReplicas: true,
  })
});

Replace "username" and "password" with your Redis credential. If that doesn't work, check that the password is correct and try again.
