### ISSUE TITLE
Suitable way to pass messages from job to outside world?

### ISSUE THREAD

**Issue by lf94** [bee-queue/bee-queue#57]
It would be nice to store or emit "job messages" somewhere.

Maybe this would be suitable to put it in reportProgress, like this:

```
job.reportProgress(50, 'This is a message')
job.reportProgress(50, 'Another message, but doesn't mean we have progressed any further')
```

This would make extending the 'job progress' and 'progress' events backwards compatible:

```
/* Old */
queue.on('job progress', (id, progress) => {})

/* New */
queue.on('job progress', (id, progress, msg) => {})
```

The only issue with this is we lose this information on each progress report. Some may want to keep all job output. A use case for this is when you start-up an application, you want to see all output from all jobs. Or you click on a job and want to see more details (like its output).

Currently I'm passing a websocket connection and emitting a message within my job to all clients. I kind of have a job dashboard going on, but it isn't the greatest because of the parallel nature of job processing.

It works like this:

Job id: [ Updates on every websocket message - could change to any id being reported by bee-queue ]
Job progress: [ Progress for the job id ]
Output:
[ Textarea with all output from all jobs coming in - which means it is a mix of output. ]

Since there can be 1000+ jobs I can't see a more efficient way to display output. The textarea holds about 2000 lines. I had thought about using a table with progress bars and when you click the row it expands to show the output, but there would be too much (1000+ rows).

It would be much better to emit events within the job rather than do this. For example:
```
function doThing(job) {
    job.emit('message', 'hiiiii')
    doMore();
}

// Send all messages from this job to all clients connected to us
job.on('message', (msg) => { wss.clients.forEach((ws) => ws.send(msg)) })
```
What's everyone's thoughts on this? What do you do to report messages to other components?

**Comment by skeggse** [comment]
I'm not entirely clear on your use-case here, but it seems like this is outside the scope of a job queue.

If you need to post specific messages to specific clients during job processing, that's a separate concern from the processing of the job itself. You should probably have a separate channel for message passing to clients, as you might want to use that same channel from outside job processing.
