### ISSUE TITLE
Is there a way to clean old queues ?

### ISSUE THREAD

**Issue by amelon-bflo** [bee-queue/bee-queue#58]
Hello,

our redis base is becoming very huge.
I just discovered option `removeOnSuccess` option and set it to true.

But do you have script or anything else, to clean successed queues and even old error queues?

thanks

**Comment by LewisJEllis** [comment]
You should be able to just go into a redis cli and run some SREMs, HDELs, etc. The [under the hood section](https://github.com/LewisJEllis/bee-queue#under-the-hood) describes which keys are used for what. Just be careful not to delete anything being used for a waiting/active job - if you blindly delete all keys in the `bq:queuename:jobs` hash, you might accidentally delete job data for an in-progress job, so use keys from `bq:queuename:succeeded` and `bq:queuename:failed` instead or something like that.

Alternatively, a more complicated but safer option would be to change your queue name string, restart everything using that queue name string (in an order that ensures you don't leave jobs on the old queue name unprocessed - i.e. restart all producers first, then restart all consumers, or more staggered if you want to avoid a latency spike during restart), and then delete all data on the old queue name once everything is running on the new one.

**Comment by skeggse** [comment]
It seems that one way forward here would be to add this kind of bulk operational functionality to Arena (we're retrofitting Bull Arena, a UI for Bull, to [work with Bee](https://github.com/mixmaxhq/arena/tree/bee-queue)).

**Comment by skeggse** [comment]
Given that we've release `1.0.0`, you can solve this problem with Arena. If you'd like a different solution to your problem, feel free to reopen.
