### ISSUE TITLE
Pause/Retry documentation

### ISSUE THREAD

**Issue by saadjhk** [bee-queue/bee-queue#593]
Hi, i was wondering if there is documentation available for pausing a queue for maintenance purpose.

I see there is a `paused` option but Im not sure how to correctly use it if i want to wait for current jobs to be completed and then pause queues to update the server

**Comment by compwright** [comment]
@saadjhk in the future please use the Discussions tab for questions like this. Use Issues for reporting bugs only.

However, I will answer your question. I think it would make sense to handle this by simply stopping all your queue workers while you do maintenance, and starting them up again when you are done.
