### ISSUE TITLE
Cannot find type definition file for 'redis'

### ISSUE THREAD

**Issue by cleytoncarvalho** [bee-queue/bee-queue#607]
I'm facing this error when trying to build my app:

<img width="884" alt="Captura de Tela 2023-03-11 às 11 02 56" src="https://user-images.githubusercontent.com/7952866/224489102-0554b116-ed01-4718-b15e-68eaa5f84974.png">

I'm using pnpm as package manager.

**Comment by warstrolo** [comment]
@cleytoncarvalho This is not linked to the package manager but the TypeScript compilator that try to check lib types and find that redis definition is missing.

To address and fix this issue and other "type check" issues that might come from your imported libs, you set the `skipLibCheck : true` flag to TypeScript compilator

```json
{
  "compilerOptions": {
        "skipLibCheck": true,
   }
}
```

**Comment by cleytoncarvalho** [comment]
@warstrolo Thanks!! It worked.
