### ISSUE TITLE
Is there a way to save the job result (or error) in the job itself

### ISSUE THREAD

**Issue by squallstar** [bee-queue/bee-queue#61]
As the title says, I'd like to save the job result and its error on the job object, since I'm not removing them on success.

Is there a way to achieve this?

I've tried to hijack the `job` on the processing like 

```js
job.data.result = result;
job.save();
```

But the above causes a new job to be created (hence a loop). Any advice would be great.

Thanks!

**Comment by skeggse** [comment]
There isn't currently a way to save job results on the job itself, as this is mostly out-of-scope for a job queue. You can save job results to external databases or data stores, or you can produce new jobs on a separate `Queue` to store (and later consume) the result of their operation.

Reopen this issue if you can define a concrete use-case that requires the described functionality.
