### ISSUE TITLE
Question: How to enqueue job without waiting for results?

### ISSUE THREAD

**Issue by pulkitsinghal** [bee-queue/bee-queue#62]
In the [long](https://github.com/LewisJEllis/bee-queue/wiki/Origin) explanation behind bee-queue's inception, the following usecase is mentioned:
> Receive request -> Enqueue job -> Send response -> Retrieve results later

I'm wondering how to make it happen so that the producer can enqueue a job (successfully) and then move on ... without waiting for results.

> getEvents: boolean, default true. Disable if this queue does not need to receive job events.

Would setting `getEvents:false` allow me to do this? Or is there some other way?

**Comment by grantcarthew** [comment]
@pulkitsinghal please see #63

**Comment by skeggse** [comment]
If I understand correctly, you do not need to retrieve the result of jobs for your use-case. We introduce a number of additional configuration parameters in #64, in which setting `getEvents`, `sendEvents`, `storeJobs` all to `false` will disable the systems to support returning results to the producer.
