### ISSUE TITLE
This queue is dead (maybe not)

### ISSUE THREAD

**Issue by grantcarthew** [bee-queue/bee-queue#63]
Reference: https://github.com/LewisJEllis/bee-queue/commits/master

At the time of opening this issue the last commit to master was on Feb 2016.

Someone can fork it and take up the banner.

I made [my own](https://www.npmjs.com/package/rethinkdb-job-queue) using this project for inspiration so am not interested. Anyone?

**Comment by bradvogel** [comment]
hey - we're working on reviving it. Stay tuned!

**Comment by thelinuxlich** [comment]
It will be difficult to use this library now that Bull evolved so much.

**Comment by bradvogel** [comment]
Yes, this revival will be a simplified performance-optimized version of Bull for very-high-throughput queues. It won't have nearly the number of features though.

**Comment by skeggse** [comment]
Closing as duplicate of #45.
