### ISSUE TITLE
When using the bun runtime, the succeeded event does not receive the result

### ISSUE THREAD

**Issue by jdgriffith** [bee-queue/bee-queue#658]
I really like the lightweight aspect of bee-queue and hope development of this continues! 

I'm trying to switch to the bun runtime and I know the default answer might be you don't support this runtime but I thought I would ask this question in case there is a simple top of mind reason for why this is happening. 

```
queue.process( async (job, done) => {
    try {
      console.log(`processing job ${job.id}`)

      const security = JSON.parse(JSON.stringify(job.data.security))
      await securityStatistics.updateSecurityStatistics(security, false)

      return done(null, security)
    } catch (error) {
        console.error(error)

        return done(error)
    }
})
```

```
job.on('succeeded', (result) => {
            console.timeEnd(`statistics_${timeUUID}`)
            console.log(`Received result for job ${job.id}: `, result)
})
```

I am receiving the succeeded event but for some reason `result` is undefined. I have tested this in several different ways and am still receiving the same undefined value. Any ideas what could be happening here? 

Thanks for any help/thoughts on this matter!

**Comment by compwright** [comment]
Best to use the discussions area for things like this which are not bug reports.

You shouldn't mix the callback and promise paradigms. I would recommend you try the following:

```javascript
queue.process(async function (job) {
  console.log(`processing job ${job.id}`)
  const security = JSON.parse(JSON.stringify(job.data.security))
  await securityStatistics.updateSecurityStatistics(security, false)
  return security
})
```

Beyond that, when using a new and potentially immature runtime, it's advisable to first make sure your code works with a well established runtime like Node.js 16.x or 18.x and see if it runs as expected to rule out bugs in your code.

**Comment by compwright** [comment]
@jdgriffith glad it works! The docs don't mix the paradigms, they use the callback paradigm. When async/await is introduced, you MUST use the promise paradigm and NOT the callback paradigm.
