### ISSUE TITLE
BUG: Crashed when build using webpack.

### ISSUE THREAD

**Issue by mai1x9** [bee-queue/bee-queue#689]
```
/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/master/node_modules/redis/index.js:850
            var undefinedArgError = new Error(
                                    ^

Error: node_redis: The EVALSHA command contains a invalid argument type of "undefined".
Only strings, dates and buffers are accepted. Please update your code to use valid argument types.
    at RedisClient.internal_send_command (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/master/node_modules/redis/index.js:850:37)
    at RedisClient.evalsha (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/master/node_modules/redis/lib/commands.js:46:25)
    at /home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/master/dist/app.js:1:400337
    at /home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/master/dist/app.js:1:413430
    at new Promise (<anonymous>)
    at Object._0x3a63d8 [as callAsync] (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/master/dist/app.js:1:413381)
    at _0x18fa22._evalScriptOn (/home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/master/dist/app.js:1:400212)
    at /home/lns_vm05/Desktop/SuperAdmin_beta_v0.1.8/master/dist/app.js:1:400692
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  command: 'EVALSHA',
  args: [
    undefined,
    3,
    'bq:ci-cd-server:id',
    'bq:ci-cd-server:jobs',
    'bq:ci-cd-server:waiting',
    'ba8c02d6-bcf5-4b34-9be9-902ec50f87e0',
    '{"data":{"id":46,"rid":62,"nid":69,"start":1694108130426,"execute":"node"},"options":{"timestamp":1694108130429,"stacktraces":[],"retries":0,"timeout":10000},"status":"created","progress":0}'
  ]
}
```

**Comment by wzulfikar** [comment]
Got the same issue when using nextjs

**Comment by paambaati** [comment]
Noticing this issue when running in an Remix action as well, even though it clearly runs only server-side.

**Comment by paambaati** [comment]
@compwright Would you be able to provide any insights here? I can tell that `lua` is an empty object (`{}`) at this point – https://github.com/bee-queue/bee-queue/blob/f6d901308f3b6433f2531edc4a9ac354aab434e5/lib/queue.js#L875-L882

**Comment by paambaati** [comment]
@compwright I have, its on.

Remix and Next.js both have ways to specifically say which bits run on the server, and which run on the client-side. In my case, using Remix, I had specifically made sure all the `bee-queue` logic was running purely on the server-side.

My guess is there's some subtle bug in the way the package is bundled in these runtimes.

**Comment by compwright** [comment]
@paambaati please try excluding this package in your remix.config.js, see https://remix.run/docs/en/main/file-conventions/remix-config#serverdependenciestobundle

**Comment by paambaati** [comment]
@compwright I’ve tried that with no luck.

**Comment by compwright** [comment]
@paambaati can you provide a complete code example that reproduces the issue? A public stand-alone repository, with only enough code to reproduce the problem. Test it, make sure you get the same error, and then post it here.

**Comment by compwright** [comment]
Closing due to no response.

**Comment by jkrehm** [comment]
@compwright I know I'm late to this ticket, but I just ran into the issue and I have created a minimal Next.js application to recreate the issue. Would you be willing to take a look?

https://github.com/jkrehm/bee-queue-nextjs
