### ISSUE TITLE
Crash app when redis connection is wrong

### ISSUE THREAD

**Issue by giang21199z** [bee-queue/bee-queue#691]
Hi Bee-queue dev team.
I faced to node-app crash when redis connection refused. I can't start application with wrong redis url.
This is log exception from bee-queue.
```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ECONNREFUSED 10.128.abc.xyz:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.128.abc.xyz',
  port: 6379
}
[nodemon] app crashed - waiting for file changes before starting...
```

```
node version: v16.15.1
"bee-queue": "^1.5.0",
```

Reproduce:
Try to wrong redis url configuration.

Thank you.

**Comment by compwright** [comment]
This is not a bug, not sure why you are reporting it as one. Obviously, you're going to get an error when you try to connect to the wrong address.
