### ISSUE TITLE
Is `Queue#removeJob` considered unstable?

### ISSUE THREAD

**Issue by kjellmorten** [bee-queue/bee-queue#72]
I discovered the `removeJob` method in `lib/queue.js`, but it's not in the documentation.

Should I expect to the method to change at some point, or is it just missing in the docs?

I'll be happy to add it to the README, if it is the latter case. :)

**Comment by LewisJEllis** [comment]
I would say it is considered stable, just not added to the readme. We have some tests for it behavior and it is used by the configuration flags `removeOnSuccess` and `removeOnFailure`. It is also exposed via `Job#remove`, which is also undocumented.

In those docs I would 1) encourage users to utilize the `removeOnSuccess/Failure` config flags instead if possible, and 2) warn users to be careful not to remove jobs before they've been fully processed; there are probably scenarios that we have not tried to account for where that would result in undefined or undesirable behavior.

Out of curiosity, do you have a specific use case for this that we might be able to better support? I'm sure there are plenty of good uses, but my hope is that the `removeOnSuccess/Failure` flags would cover almost all of them.

**Comment by kjellmorten** [comment]
Ok, thanks!

The current use case is for integration tests in a project where I use Bee-Queue. I clean up after the tests with `Queue#removeJob`.

Further down the line, I will probably have the need for flushing completed jobs etc. I saw that you discussed this in another issue, and concluded for now that having the possibility to clear queues in Arena is sufficient. It makes sense to have a flush mechanism in Bee-Queue as well, but so far `removeJob` and `Job#remove` will probably do.

**Comment by LewisJEllis** [comment]
Ah okay, yep it should be totally fine to use for integration tests. In that case you might also make use of [Queue#destroy](https://github.com/bee-queue/bee-queue/blob/master/lib/queue.js#L231), which of course is also currently undocumented.

**Comment by kjellmorten** [comment]
Yes, I see. `Queue#destroy` removes every key belonging to the queue in Redis. That's even better in a test.

Thanks, I'll have a look at it.

**Comment by kjellmorten** [comment]
@LewisJEllis, I took a shot at documenting these methods. See #74.
