### ISSUE TITLE
Dynamic retry of Job based on error details

### ISSUE THREAD

**Issue by AMWN** [bee-queue/bee-queue#722]
I'm looking for a way to retry a job depending on the error I got from an http request. 
So when I read the documentation I only see the possibility to give a fixed retries parameter in the job options.

In this case I receive from a webservice a http response. When it has http status 503 or 504 I would like to retry.

What would be the correct way to implement this?

**Comment by compwright** [comment]
In your worker, you should catch the web service errors in a try...catch block and decide there how to handle the error. For the errors you want to retry, re-throw the error inside the catch block. For the errors you do not want to retry, do not throw. Log, send the error somewhere (like Sentry), or return some response, but don't throw any error you don't want retried.

**Comment by compwright** [comment]
For future reference, please use the discussions tab for questions about how to use bee-queue, and use the issues tab to report bugs or request features.
