### ISSUE TITLE
Performance differences on Node 6 vs 7 vs 8

### ISSUE THREAD

**Issue by LewisJEllis** [bee-queue/bee-queue#79]
In #69:

> If I'm interpreting these numbers correctly, it looks like bee-queue is significantly faster on Node 7 and even 6 than on 8, while other queues exhibit more consistent performance numbers across Node versions. Any idea why that might be? Is it worth pointing out in the readme? It looks like we get a 50% throughput boost just by running on 7 instead of 8.
  
It doesn't seem to make immediate sense that the node version would have such drastic impact. Investigate more.

**Comment by compwright** [comment]
We are dropping support for these versions
