### ISSUE TITLE
Preserve succeeded job payload

### ISSUE THREAD

**Issue by timboudreau** [bee-queue/bee-queue#84]
We're using bee-queue for media transcoding.  So essentially:

 * Worker processes some bytes, generates a pile of output files, sends them somewhere
 * Another process listening on the queue receives progress/success/failure notifications, and updates a database, sends messages over NATS to a webapp that translates those into websocket messages, and deletes succeeded jobs once that completes successfully - so workers are simple and do work, and can keep working even if other things are down

This all works, except that it's important that the database eventually gets updated even if the notification-receiving process is down when a job completes.  A straightforward solution would be, on startup, iterate any non-deleted, succeeded jobs and send their payloads along.  But, alas, the succeeded jobs are there, but the payload passed when they succeeded has gone into a black hole.

This can be worked around by having workers enqueue the job-success payload into yet another queue, and send from that - but this seems like a hack around something very basic and simple that would be easy enough to do.

Looking at the code, it ought to be pretty straightforward to save the success payload the same way error stack traces are saved.

**Comment by Kamshak** [comment]
Very similar use case here, same problem. @timboudreau how did you solve this in the end? @skeggse any thoughts?

**Comment by timboudreau** [comment]
Right now, a worker that succeeded creates a new job in a "success" queue, and that gets processed separately to update the database.

**Comment by Kamshak** [comment]
Just found that out as well! For anyone reading this later you can change job.data before returning from the handler and that will be persisted to the db as well.

**Comment by timboudreau** [comment]
Ugly but better than nothing I guess.

**Comment by skeggse** [comment]
>This can be worked around by having workers enqueue the job-success payload into yet another queue, and send from that - but this seems like a hack around something very basic and simple that would be easy enough to do.

This is currently the recommended solution - multiple queues ensures a separation of concerns between the handling of the job, and subsequent updating when a job finishes. Feel free to propose and justify an API change that exposes the functionality you'd like to see, or build a module on top of bee-queue that adds the features you want. We'd like to keep bee-queue small and simple, so any changes like this need to be balanced against the additional cost to bee-queue's core.
