### ISSUE TITLE
Jobqueue show error when the same job with same data reschedule when the first one is over

### ISSUE THREAD

**Issue by rajatprogrammer** [bee-queue/bee-queue#86]
I have a set of data and using bee-queue I create a job for first time and it successfully completed and in setting of job I customised that if successfully job completed remove from Redis and when i again call the job process it gives error  like and I also open queue.js  file

error logs
< /home/silver/background_jobs/node_modules/bee-queue/lib/queue.js:583
<       throw new Error('Cannot call Queue#process twice');
<       ^
< Error: Cannot call Queue#process twice
<     at Queue.process (/home/silver/background_jobs/node_modules/bee-queue/lib/queue.js:583:13)
<     at Object.processJob (/home/silver/background_jobs/server/lib/crownjobs.js:35:18)
<     at /home/silver/background_jobs/server/lib/jobsTypes.js:23:31
<     at Command.callback (/home/silver/background_jobs/server/lib/jobsTypes.js:14:24)
<     at normal_reply (/home/silver/background_jobs/node_modules/redis/index.js:726:21)
<     at RedisClient.return_reply (/home/silver/background_jobs/node_modules/redis/index.js:824:9)
<     at JavascriptRedisParser.returnReply (/home/silver/background_jobs/node_modules/redis/index.js:192:18)
<     at JavascriptRedisParser.execute (/home/silver/background_jobs/node_modules/redis-parser/lib/parser.js:574:12)
<     at Socket.<anonymous> (/home/silver/background_jobs/node_modules/redis/index.js:274:27)
<     at emitOne (events.js:96:13)

But if the first process is over then it schedules for the second it fine...

My operation is to call 2 api from the crown job it schedule the job calling sequence.....

**Comment by LewisJEllis** [comment]
You shouldn't need to call `queue.process()` more than once. Perhaps a more descriptive name for the method would be `queue.beginProcessing()` - calling it once makes the process that called it automatically process jobs as long as there are jobs to be processed.
