### ISSUE TITLE
Flaky "distant delayed job" test failure on Node 9

### ISSUE THREAD

**Issue by LewisJEllis** [bee-queue/bee-queue#93]
Worked after restarting a build; error message seemed to indicate the timing assertion was off by a millisecond or a second.

**Comment by dylanjha** [comment]
There's a few suspicious lines that could be the cause https://github.com/bee-queue/bee-queue/blob/master/test/delay-test.js#L164:

> queue.createJob({is: 'distant'}).delayUntil(start + 150)
> helpers.delay(Date.now() - start + 151)
>  t.is(await scheduled, start + 150)
> t.true(Date.now() >= start + 150)

I ran `npm test` 10 times on `node v9.5.0` and could not get this to fail a single time. I wonder if what you saw is actually Node 9 specific or if you got lucky. Tough to debug this one, I tried adding a 10ms delay after every line of this test to try to force this bug, but even then, no luck :/.

If you run into this again see if you can post the error message and I'll debug it further

**Comment by LewisJEllis** [comment]
Yea, I wasn't immediately sure either, and I never reproduced it locally, just ran into it on travis - hard to say. I'll update here if it happens again.
