### ISSUE TITLE
Failure running bee-queue example script.

### ISSUE THREAD

**Issue by yaducam** [bee-queue/bee-queue#99]
Hello,

I'm new to bee-queue.
I'm running on debian 8, node version : v6.11.3, redis-server : redis-cli 4.0.6
I trying to run the example script provided in the README :

const Queue = require('bee-queue');
const queue = new Queue('example');

const job = queue.createJob({x: 2, y: 3}).save();
job.on('succeeded', (result) => {
  console.log(`Received result for job ${job.id}: result`);
});

// Process jobs from as many servers or processes as you like
queue.process(function (job, done) {
  console.log(`Processing job ${job.id}`);
  return done(null, job.data.x + job.data.y);
});

But this is what i get : 
/home/julien/beeQ/testBQ.js:12
job.on('succeeded', (result) => {
    ^

TypeError: job.on is not a function
    at Object.<anonymous> (/home/julien/beeQ/testBQ.js:12:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

Any idea why ?

**Comment by LewisJEllis** [comment]
Can you paste the exact contents of `testBQ.js`? In the example, `job.on` is line 4, but in your stack trace it is line 12.

**Comment by yaducam** [comment]
Yes.. Sorry, i tried to customize/debug a bit the script, that's why it 's showing line 12.

So i startover with a new file where i copy/paste the sample script provided in the readme. 

more <Pathname>/sample.js 
const Queue = require('bee-queue');
const queue = new Queue('example');

const job = queue.createJob({x: 2, y: 3}).save();
job.on('succeeded', (result) => {
  console.log(`Received result for job ${job.id}: result`);
});

// Process jobs from as many servers or processes as you like
queue.process(function (job, done) {
  console.log(`Processing job ${job.id}`);
  return done(null, job.data.x + job.data.y);
});

And the result :  

<Pathname>/sample.js:5
job.on('succeeded', (result) => {
    ^

TypeError: job.on is not a function
    at Object.<anonymous> (<Pathname>/sample.js:5:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
ult :

**Comment by dturton** [comment]
Getting the same error. TypeError: job.on is not a function

**Comment by LewisJEllis** [comment]
Ah, okay - this was an artifact of the transition to a promise-based API. `job.save()` now returns a promise instead of a job instance. I'll update the readme example. Thanks for reporting!

**Comment by yaducam** [comment]
The Readme change didn't fix the problem :-(.
job.save() is working fine. look like job.on() is the problem here.
